/* Urząd skarbowy + oddział NFZ właściwe dla kodu pocztowego adresu zamieszkania.
   Kod pocztowy -> gmina/powiat/województwo (kodpocztowy.intami.pl), następnie:
   - NFZ: jeden oddział wojewódzki na województwo,
   - US: wg załącznika nr 2 do rozporządzenia o terytorialnym zasięgu działania
     naczelników urzędów skarbowych (Dz.U. 2022 poz. 361). Dane wygenerowane z
     tekstu aktu: n = nazwa, w = województwo, p = całe powiaty, g = gminy części
     powiatu, c = miasta na prawach powiatu, d = nazwane części (dzielnice) miasta.
     W miastach z kilkoma urzędami część granic biegnie ulicami — gdy dzielnica nie
     rozstrzyga, zwracamy listę kandydatów zamiast jednego urzędu. */
(function () {
  'use strict';
  var API = 'https://kodpocztowy.intami.pl/api/';

  var NFZ = {
    'dolnośląskie': 'Dolnośląski OW NFZ (01R)', 'kujawsko-pomorskie': 'Kujawsko-Pomorski OW NFZ (02R)',
    'lubelskie': 'Lubelski OW NFZ (03R)', 'lubuskie': 'Lubuski OW NFZ (04R)',
    'łódzkie': 'Łódzki OW NFZ (05R)', 'małopolskie': 'Małopolski OW NFZ (06R)',
    'mazowieckie': 'Mazowiecki OW NFZ (07R)', 'opolskie': 'Opolski OW NFZ (08R)',
    'podkarpackie': 'Podkarpacki OW NFZ (09R)', 'podlaskie': 'Podlaski OW NFZ (10R)',
    'pomorskie': 'Pomorski OW NFZ (11R)', 'śląskie': 'Śląski OW NFZ (12R)',
    'świętokrzyskie': 'Świętokrzyski OW NFZ (13R)', 'warmińsko-mazurskie': 'Warmińsko-Mazurski OW NFZ (14R)',
    'wielkopolskie': 'Wielkopolski OW NFZ (15R)', 'zachodniopomorskie': 'Zachodniopomorski OW NFZ (16R)',
  };

  var US = [{"n":"Urząd Skarbowy w Bolesławcu","w":"dolnośląskie","p":["bolesławiecki"]},
    {"n":"Urząd Skarbowy w Bystrzycy Kłodzkiej","w":"dolnośląskie","g":{"kłodzki":["Bystrzyca Kłodzka","Lądek-Zdrój","Międzylesie","Stronie Śląskie"]}},
    {"n":"Urząd Skarbowy w Dzierżoniowie","w":"dolnośląskie","p":["dzierżoniowski"]},
    {"n":"Urząd Skarbowy w Głogowie","w":"dolnośląskie","p":["głogowski"]},
    {"n":"Urząd Skarbowy w Górze","w":"dolnośląskie","p":["górowski"]},
    {"n":"Urząd Skarbowy w Jaworze","w":"dolnośląskie","p":["jaworski"]},
    {"n":"Urząd Skarbowy w Jeleniej Górze","w":"dolnośląskie","p":["karkonoski"],"c":["Jelenia Góra"]},
    {"n":"Urząd Skarbowy w Kamiennej Górze","w":"dolnośląskie","p":["kamiennogórski"]},
    {"n":"Urząd Skarbowy w Kłodzku","w":"dolnośląskie","g":{"kłodzki":["Duszniki-Zdrój","Kłodzko","Kudowa-Zdrój","Polanica-Zdrój","Lewin Kłodzki","Szczytna"]}},
    {"n":"Urząd Skarbowy w Legnicy","w":"dolnośląskie","p":["legnicki"],"c":["Legnica"]},
    {"n":"Urząd Skarbowy w Lubaniu","w":"dolnośląskie","p":["lubański"]},
    {"n":"Urząd Skarbowy w Lubinie","w":"dolnośląskie","p":["lubiński"]},
    {"n":"Urząd Skarbowy w Lwówku Śląskim","w":"dolnośląskie","p":["lwówecki"]},
    {"n":"Urząd Skarbowy w Miliczu","w":"dolnośląskie","p":["milicki"]},
    {"n":"Urząd Skarbowy w Nowej Rudzie","w":"dolnośląskie","g":{"kłodzki":["Nowa Ruda","Radków"]}},
    {"n":"Urząd Skarbowy w Oleśnicy","w":"dolnośląskie","p":["oleśnicki"]},
    {"n":"Urząd Skarbowy w Oławie","w":"dolnośląskie","p":["oławski"]},
    {"n":"Urząd Skarbowy w Polkowicach","w":"dolnośląskie","p":["polkowicki"]},
    {"n":"Urząd Skarbowy w Strzelinie","w":"dolnośląskie","p":["strzeliński"]},
    {"n":"Urząd Skarbowy w Środzie Śląskiej","w":"dolnośląskie","p":["średzki"]},
    {"n":"Urząd Skarbowy w Świdnicy","w":"dolnośląskie","p":["świdnicki"]},
    {"n":"Urząd Skarbowy w Trzebnicy","w":"dolnośląskie","p":["trzebnicki"]},
    {"n":"Urząd Skarbowy w Wałbrzychu","w":"dolnośląskie","p":["wałbrzyski"],"c":["Wałbrzych"]},
    {"n":"Urząd Skarbowy w Wołowie","w":"dolnośląskie","p":["wołowski"]},
    {"n":"Urząd Skarbowy Wrocław-Fabryczna","w":"dolnośląskie","c":["Wrocław"],"d":["Fabryczna"]},
    {"n":"Urząd Skarbowy Wrocław-Krzyki","w":"dolnośląskie","c":["Wrocław"],"d":["Krzyki"]},
    {"n":"Urząd Skarbowy Wrocław-Psie Pole","w":"dolnośląskie","c":["Wrocław"],"d":["Psie Pole"]},
    {"n":"Urząd Skarbowy Wrocław-Stare Miasto","w":"dolnośląskie","c":["Wrocław"],"d":["Stare Miasto"]},
    {"n":"Urząd Skarbowy Wrocław-Śródmieście","w":"dolnośląskie","c":["Wrocław"],"d":["Śródmieście"]},
    {"n":"Pierwszy Urząd Skarbowy we Wrocławiu","w":"dolnośląskie","p":["wrocławski"]},
    {"n":"Urząd Skarbowy w Ząbkowicach Śląskich","w":"dolnośląskie","p":["ząbkowicki"]},
    {"n":"Urząd Skarbowy w Zgorzelcu","w":"dolnośląskie","p":["zgorzelecki"]},
    {"n":"Urząd Skarbowy w Złotoryi","w":"dolnośląskie","p":["złotoryjski"]},
    {"n":"Urząd Skarbowy w Aleksandrowie Kujawskim","w":"kujawsko-pomorskie","p":["aleksandrowski"]},
    {"n":"Urząd Skarbowy w Brodnicy","w":"kujawsko-pomorskie","p":["brodnicki"]},
    {"n":"Pierwszy Urząd Skarbowy w Bydgoszczy","w":"kujawsko-pomorskie","p":["bydgoski"],"c":["Bydgoszcz"]},
    {"n":"Drugi Urząd Skarbowy w Bydgoszczy","w":"kujawsko-pomorskie","c":["Bydgoszcz"]},
    {"n":"Trzeci Urząd Skarbowy w Bydgoszczy","w":"kujawsko-pomorskie","c":["Bydgoszcz"]},
    {"n":"Urząd Skarbowy w Chełmnie","w":"kujawsko-pomorskie","p":["chełmiński"]},
    {"n":"Urząd Skarbowy w Grudziądzu","w":"kujawsko-pomorskie","p":["grudziądzki"],"c":["Grudziądz"]},
    {"n":"Urząd Skarbowy w Inowrocławiu","w":"kujawsko-pomorskie","p":["inowrocławski"]},
    {"n":"Urząd Skarbowy w Lipnie","w":"kujawsko-pomorskie","p":["lipnowski"]},
    {"n":"Urząd Skarbowy w Mogilnie","w":"kujawsko-pomorskie","p":["mogileński"]},
    {"n":"Urząd Skarbowy w Nakle n. Notecią","w":"kujawsko-pomorskie","p":["nakielski"]},
    {"n":"Urząd Skarbowy w Radziejowie","w":"kujawsko-pomorskie","p":["radziejowski"]},
    {"n":"Urząd Skarbowy w Rypinie","w":"kujawsko-pomorskie","p":["rypiński"]},
    {"n":"Urząd Skarbowy w Świeciu","w":"kujawsko-pomorskie","p":["świecki"]},
    {"n":"Pierwszy Urząd Skarbowy w Toruniu","w":"kujawsko-pomorskie","c":["Toruń"]},
    {"n":"Drugi Urząd Skarbowy w Toruniu","w":"kujawsko-pomorskie","p":["toruński"],"c":["Toruń"]},
    {"n":"Urząd Skarbowy w Tucholi","w":"kujawsko-pomorskie","p":["tucholski"]},
    {"n":"Urząd Skarbowy w Sępólnie Krajeńskim","w":"kujawsko-pomorskie","p":["sępoleński"]},
    {"n":"Urząd Skarbowy w Wąbrzeźnie","w":"kujawsko-pomorskie","p":["wąbrzeski"]},
    {"n":"Urząd Skarbowy w Golubiu-Dobrzyniu","w":"kujawsko-pomorskie","p":["golubsko-dobrzyński"]},
    {"n":"Urząd Skarbowy we Włocławku","w":"kujawsko-pomorskie","p":["włocławski"],"c":["Włocławek"]},
    {"n":"Urząd Skarbowy w Żninie","w":"kujawsko-pomorskie","p":["żniński"]},
    {"n":"Urząd Skarbowy w Białej Podlaskiej","w":"lubelskie","p":["bialski"],"c":["Biała Podlaska"]},
    {"n":"Urząd Skarbowy w Biłgoraju","w":"lubelskie","p":["biłgorajski"]},
    {"n":"Urząd Skarbowy w Chełmie","w":"lubelskie","p":["chełmski"],"c":["Chełm"]},
    {"n":"Urząd Skarbowy w Hrubieszowie","w":"lubelskie","p":["hrubieszowski"]},
    {"n":"Urząd Skarbowy w Janowie Lubelskim","w":"lubelskie","p":["janowski"]},
    {"n":"Urząd Skarbowy w Krasnymstawie","w":"lubelskie","p":["krasnostawski"]},
    {"n":"Urząd Skarbowy w Kraśniku","w":"lubelskie","p":["kraśnicki"]},
    {"n":"Urząd Skarbowy w Lubartowie","w":"lubelskie","p":["lubartowski"]},
    {"n":"Pierwszy Urząd Skarbowy w Lublinie","w":"lubelskie","p":["świdnicki"],"c":["Lublin"]},
    {"n":"Drugi Urząd Skarbowy w Lublinie","w":"lubelskie","p":["lubelski"]},
    {"n":"Trzeci Urząd Skarbowy w Lublinie","w":"lubelskie","c":["Lublin"]},
    {"n":"Urząd Skarbowy w Łęcznej","w":"lubelskie","p":["łęczyński"]},
    {"n":"Urząd Skarbowy w Łukowie","w":"lubelskie","p":["łukowski"]},
    {"n":"Urząd Skarbowy w Opolu Lubelskim","w":"lubelskie","p":["opolski"]},
    {"n":"Urząd Skarbowy w Parczewie","w":"lubelskie","p":["parczewski"]},
    {"n":"Urząd Skarbowy w Puławach","w":"lubelskie","p":["puławski"]},
    {"n":"Urząd Skarbowy w Radzyniu Podlaskim","w":"lubelskie","p":["radzyński"]},
    {"n":"Urząd Skarbowy w Rykach","w":"lubelskie","p":["rycki"]},
    {"n":"Urząd Skarbowy w Tomaszowie Lubelskim","w":"lubelskie","p":["tomaszowski"]},
    {"n":"Urząd Skarbowy we Włodawie","w":"lubelskie","p":["włodawski"]},
    {"n":"Urząd Skarbowy w Zamościu","w":"lubelskie","p":["zamojski"],"c":["Zamość"]},
    {"n":"Urząd Skarbowy w Drezdenku","w":"lubuskie","p":["strzelecko-drezdenecki"]},
    {"n":"Urząd Skarbowy w Gorzowie Wielkopolskim","w":"lubuskie","p":["gorzowski"],"c":["Gorzów Wielkopolski"]},
    {"n":"Urząd Skarbowy w Krośnie Odrzańskim","w":"lubuskie","p":["krośnieński"]},
    {"n":"Urząd Skarbowy w Międzyrzeczu","w":"lubuskie","p":["międzyrzecki"]},
    {"n":"Urząd Skarbowy w Nowej Soli","w":"lubuskie","p":["nowosolski"]},
    {"n":"Urząd Skarbowy w Słubicach","w":"lubuskie","p":["słubicki"]},
    {"n":"Urząd Skarbowy w Sulęcinie","w":"lubuskie","p":["sulęciński"]},
    {"n":"Urząd Skarbowy w Świebodzinie","w":"lubuskie","p":["świebodziński"]},
    {"n":"Urząd Skarbowy we Wschowie","w":"lubuskie","p":["wschowski"]},
    {"n":"Pierwszy Urząd Skarbowy w Zielonej Górze","w":"lubuskie","c":["Zielona Góra"]},
    {"n":"Drugi Urząd Skarbowy w Zielonej Górze","w":"lubuskie","p":["zielonogórski"],"c":["Zielona Góra"]},
    {"n":"Urząd Skarbowy w Żaganiu","w":"lubuskie","p":["żagański"]},
    {"n":"Urząd Skarbowy w Żarach","w":"lubuskie","p":["żarski"]},
    {"n":"Urząd Skarbowy w Bełchatowie","w":"łódzkie","p":["bełchatowski"]},
    {"n":"Urząd Skarbowy w Brzezinach","w":"łódzkie","p":["brzeziński"]},
    {"n":"Urząd Skarbowy w Głownie","w":"łódzkie","g":{"zgierski":["Głowno","Stryków"]}},
    {"n":"Urząd Skarbowy w Kutnie","w":"łódzkie","p":["kutnowski"]},
    {"n":"Urząd Skarbowy w Łasku","w":"łódzkie","p":["łaski"]},
    {"n":"Urząd Skarbowy w Łęczycy","w":"łódzkie","p":["łęczycki"]},
    {"n":"Urząd Skarbowy w Łowiczu","w":"łódzkie","p":["łowicki"]},
    {"n":"Pierwszy Urząd Skarbowy Łódź-Bałuty","w":"łódzkie","c":["Łódź"],"d":["Bałuty"]},
    {"n":"Drugi Urząd Skarbowy Łódź-Bałuty","w":"łódzkie","c":["Łódź"],"d":["Bałuty"]},
    {"n":"Pierwszy Urząd Skarbowy Łódź-Górna","w":"łódzkie","c":["Łódź"],"d":["Górna"]},
    {"n":"Drugi Urząd Skarbowy Łódź-Górna","w":"łódzkie","c":["Łódź"],"d":["Górna"]},
    {"n":"Urząd Skarbowy Łódź-Polesie","w":"łódzkie","c":["Łódź"],"d":["Polesie"]},
    {"n":"Urząd Skarbowy Łódź-Śródmieście","w":"łódzkie","c":["Łódź"],"d":["Śródmieście"]},
    {"n":"Urząd Skarbowy Łódź-Widzew","w":"łódzkie","p":["łódzki wschodni"],"c":["Łódź"],"d":["Widzew"]},
    {"n":"Urząd Skarbowy w Opocznie","w":"łódzkie","p":["opoczyński"]},
    {"n":"Urząd Skarbowy w Pabianicach","w":"łódzkie","p":["pabianicki"]},
    {"n":"Urząd Skarbowy w Pajęcznie","w":"łódzkie","p":["pajęczański"]},
    {"n":"Urząd Skarbowy w Piotrkowie Trybunalskim","w":"łódzkie","p":["piotrkowski"],"c":["Piotrków Trybunalski"]},
    {"n":"Urząd Skarbowy w Poddębicach","w":"łódzkie","p":["poddębicki"]},
    {"n":"Urząd Skarbowy w Radomsku","w":"łódzkie","p":["radomszczański"]},
    {"n":"Urząd Skarbowy w Rawie Mazowieckiej","w":"łódzkie","p":["rawski"]},
    {"n":"Urząd Skarbowy w Sieradzu","w":"łódzkie","p":["sieradzki"]},
    {"n":"Urząd Skarbowy w Skierniewicach","w":"łódzkie","p":["skierniewicki"],"c":["Skierniewice"]},
    {"n":"Urząd Skarbowy w Tomaszowie Mazowieckim","w":"łódzkie","p":["tomaszowski"]},
    {"n":"Urząd Skarbowy w Wieluniu","w":"łódzkie","p":["wieluński"]},
    {"n":"Urząd Skarbowy w Wieruszowie","w":"łódzkie","p":["wieruszowski"]},
    {"n":"Urząd Skarbowy w Zduńskiej Woli","w":"łódzkie","p":["zduńskowolski"]},
    {"n":"Urząd Skarbowy w Zgierzu","w":"łódzkie","g":{"zgierski":["Ozorków","Zgierz","Aleksandrów Łódzki","Parzęczew"]}},
    {"n":"Urząd Skarbowy w Bochni","w":"małopolskie","p":["bocheński"]},
    {"n":"Urząd Skarbowy w Brzesku","w":"małopolskie","p":["brzeski"]},
    {"n":"Urząd Skarbowy w Chrzanowie","w":"małopolskie","p":["chrzanowski"]},
    {"n":"Urząd Skarbowy w Dąbrowie Tarnowskiej","w":"małopolskie","p":["dąbrowski"]},
    {"n":"Urząd Skarbowy w Gorlicach","w":"małopolskie","p":["gorlicki"]},
    {"n":"Pierwszy Urząd Skarbowy Kraków","w":"małopolskie","g":{"krakowski":["Czernichów","Liszki","Mogilany","Skawina","Świątniki Górne"]}},
    {"n":"Drugi Urząd Skarbowy Kraków","w":"małopolskie","g":{"krakowski":["Jerzmanowice-Przeginia","Krzeszowice","Michałowice","Skała","Sułoszowa","Wielka Wieś","Zabierzów","Zielonki"]}},
    {"n":"Urząd Skarbowy Kraków-Krowodrza","w":"małopolskie","c":["Kraków"]},
    {"n":"Urząd Skarbowy Kraków-Nowa Huta","w":"małopolskie","c":["Kraków"]},
    {"n":"Urząd Skarbowy Kraków-Podgórze","w":"małopolskie","c":["Kraków"]},
    {"n":"Urząd Skarbowy Kraków-Prądnik","w":"małopolskie","c":["Kraków"]},
    {"n":"Urząd Skarbowy Kraków-Stare Miasto","w":"małopolskie","c":["Kraków"]},
    {"n":"Urząd Skarbowy Kraków-Śródmieście","w":"małopolskie","c":["Kraków"]},
    {"n":"Urząd Skarbowy w Limanowej","w":"małopolskie","p":["limanowski"]},
    {"n":"Urząd Skarbowy w Miechowie","w":"małopolskie","p":["miechowski"]},
    {"n":"Urząd Skarbowy w Myślenicach","w":"małopolskie","p":["myślenicki"]},
    {"n":"Urząd Skarbowy w Nowym Sączu","w":"małopolskie","p":["nowosądecki"],"c":["Nowy Sącz"]},
    {"n":"Urząd Skarbowy w Nowym Targu","w":"małopolskie","p":["nowotarski"]},
    {"n":"Urząd Skarbowy w Olkuszu","w":"małopolskie","p":["olkuski"]},
    {"n":"Urząd Skarbowy w Oświęcimiu","w":"małopolskie","p":["oświęcimski"]},
    {"n":"Urząd Skarbowy w Proszowicach","w":"małopolskie","p":["proszowicki"],"g":{"krakowski":["Igołomia-Wawrzeńczyce","Iwanowice","Kocmyrzów-Luborzyca","Słomniki"]}},
    {"n":"Urząd Skarbowy w Suchej Beskidzkiej","w":"małopolskie","p":["suski"]},
    {"n":"Pierwszy Urząd Skarbowy w Tarnowie","w":"małopolskie","g":{"tarnowski":["Ciężkowice","Gromnik","Pleśna","Radłów","Wierzchosławice","Wojnicz","Zakliczyn"]},"c":["Tarnów"]},
    {"n":"Drugi Urząd Skarbowy w Tarnowie","w":"małopolskie","g":{"tarnowski":["Lisia Góra","Ryglice","Rzepiennik Strzyżewski","Skrzyszów","Szerzyny","Tarnów","Tuchów","Wietrzychowice","Żabno"]},"c":["Tarnów"]},
    {"n":"Urząd Skarbowy w Wadowicach","w":"małopolskie","p":["wadowicki"]},
    {"n":"Urząd Skarbowy w Wieliczce","w":"małopolskie","p":["wielicki"]},
    {"n":"Urząd Skarbowy w Zakopanem","w":"małopolskie","p":["tatrzański"]},
    {"n":"Urząd Skarbowy w Białobrzegach","w":"mazowieckie","p":["białobrzeski"]},
    {"n":"Urząd Skarbowy w Ciechanowie","w":"mazowieckie","p":["ciechanowski"]},
    {"n":"Urząd Skarbowy w Garwolinie","w":"mazowieckie","p":["garwoliński"]},
    {"n":"Urząd Skarbowy w Gostyninie","w":"mazowieckie","p":["gostyniński"]},
    {"n":"Urząd Skarbowy w Grodzisku Mazowieckim","w":"mazowieckie","p":["grodziski"]},
    {"n":"Urząd Skarbowy w Grójcu","w":"mazowieckie","p":["grójecki"]},
    {"n":"Urząd Skarbowy w Kozienicach","w":"mazowieckie","p":["kozienicki"]},
    {"n":"Urząd Skarbowy w Legionowie","w":"mazowieckie","p":["legionowski"]},
    {"n":"Urząd Skarbowy w Lipsku","w":"mazowieckie","p":["lipski"]},
    {"n":"Urząd Skarbowy w Łosicach","w":"mazowieckie","p":["łosicki"]},
    {"n":"Urząd Skarbowy w Makowie Mazowieckim","w":"mazowieckie","p":["makowski"]},
    {"n":"Urząd Skarbowy w Mińsku Mazowieckim","w":"mazowieckie","p":["miński"]},
    {"n":"Urząd Skarbowy w Mławie","w":"mazowieckie","p":["mławski"]},
    {"n":"Urząd Skarbowy w Nowym Dworze Mazowieckim","w":"mazowieckie","p":["nowodworski"]},
    {"n":"Urząd Skarbowy w Ostrołęce","w":"mazowieckie","p":["ostrołęcki"],"c":["Ostrołęka"]},
    {"n":"Urząd Skarbowy w Ostrowi Mazowieckiej","w":"mazowieckie","p":["ostrowski"]},
    {"n":"Urząd Skarbowy w Otwocku","w":"mazowieckie","p":["otwocki"]},
    {"n":"Urząd Skarbowy w Piasecznie","w":"mazowieckie","p":["piaseczyński"]},
    {"n":"Urząd Skarbowy w Płocku","w":"mazowieckie","p":["płocki"],"c":["Płock"]},
    {"n":"Urząd Skarbowy w Płońsku","w":"mazowieckie","p":["płoński"]},
    {"n":"Urząd Skarbowy w Pruszkowie","w":"mazowieckie","p":["pruszkowski"]},
    {"n":"Urząd Skarbowy w Przasnyszu","w":"mazowieckie","p":["przasnyski"]},
    {"n":"Urząd Skarbowy w Przysusze","w":"mazowieckie","p":["przysuski"]},
    {"n":"Urząd Skarbowy w Pułtusku","w":"mazowieckie","p":["pułtuski"]},
    {"n":"Pierwszy Urząd Skarbowy w Radomiu","w":"mazowieckie","g":{"radomski":["Pionki","Gózd","Iłża","Jastrzębia","Jedlińsk","Jedlnia-Letnisko","Skaryszew","Zakrzew"]},"c":["Radom"]},
    {"n":"Drugi Urząd Skarbowy w Radomiu","w":"mazowieckie","g":{"radomski":["Kowala","Przytyk","Wierzbica","Wolanów"]},"c":["Radom"]},
    {"n":"Urząd Skarbowy w Siedlcach","w":"mazowieckie","p":["siedlecki"],"c":["Siedlce"]},
    {"n":"Urząd Skarbowy w Sierpcu","w":"mazowieckie","p":["sierpecki"]},
    {"n":"Urząd Skarbowy w Sochaczewie","w":"mazowieckie","p":["sochaczewski"]},
    {"n":"Urząd Skarbowy w Sokołowie Podlaskim","w":"mazowieckie","p":["sokołowski"]},
    {"n":"Urząd Skarbowy w Szydłowcu","w":"mazowieckie","p":["szydłowiecki"]},
    {"n":"Urząd Skarbowy Warszawa-Bemowo","w":"mazowieckie","c":["Warszawa"]},
    {"n":"Urząd Skarbowy Warszawa-Bielany","w":"mazowieckie","p":["warszawski zachodni"],"c":["Warszawa"]},
    {"n":"Urząd Skarbowy Warszawa-Mokotów","w":"mazowieckie","c":["Warszawa"]},
    {"n":"Urząd Skarbowy Warszawa-Praga","w":"mazowieckie","c":["Warszawa"]},
    {"n":"Pierwszy Urząd Skarbowy Warszawa-Śródmieście","w":"mazowieckie","c":["Warszawa"]},
    {"n":"Drugi Urząd Skarbowy Warszawa-Śródmieście","w":"mazowieckie","c":["Warszawa"]},
    {"n":"Trzeci Urząd Skarbowy Warszawa-Śródmieście","w":"mazowieckie","c":["Warszawa"]},
    {"n":"Urząd Skarbowy Warszawa-Targówek","w":"mazowieckie","c":["Warszawa"]},
    {"n":"Urząd Skarbowy Warszawa-Ursynów","w":"mazowieckie","c":["Warszawa"]},
    {"n":"Urząd Skarbowy Warszawa-Wawer","w":"mazowieckie","c":["Warszawa"]},
    {"n":"Urząd Skarbowy Warszawa-Wola","w":"mazowieckie","c":["Warszawa"]},
    {"n":"Urząd Skarbowy w Węgrowie","w":"mazowieckie","p":["węgrowski"]},
    {"n":"Urząd Skarbowy w Wołominie","w":"mazowieckie","p":["wołomiński"]},
    {"n":"Urząd Skarbowy w Wyszkowie","w":"mazowieckie","p":["wyszkowski"]},
    {"n":"Urząd Skarbowy w Zwoleniu","w":"mazowieckie","p":["zwoleński"]},
    {"n":"Urząd Skarbowy w Żurominie","w":"mazowieckie","p":["żuromiński"]},
    {"n":"Urząd Skarbowy w Żyrardowie","w":"mazowieckie","p":["żyrardowski"]},
    {"n":"Urząd Skarbowy w Brzegu","w":"opolskie","p":["brzeski"]},
    {"n":"Urząd Skarbowy w Głubczycach","w":"opolskie","p":["głubczycki"]},
    {"n":"Urząd Skarbowy w Kędzierzynie-Koźlu","w":"opolskie","p":["kędzierzyńsko-kozielski"]},
    {"n":"Urząd Skarbowy w Kluczborku","w":"opolskie","p":["kluczborski"]},
    {"n":"Urząd Skarbowy w Krapkowicach","w":"opolskie","p":["krapkowicki"]},
    {"n":"Urząd Skarbowy w Namysłowie","w":"opolskie","p":["namysłowski"]},
    {"n":"Urząd Skarbowy w Nysie","w":"opolskie","p":["nyski"]},
    {"n":"Urząd Skarbowy w Oleśnie","w":"opolskie","p":["oleski"]},
    {"n":"Pierwszy Urząd Skarbowy w Opolu","w":"opolskie","c":["Opole"]},
    {"n":"Drugi Urząd Skarbowy w Opolu","w":"opolskie","p":["opolski"],"c":["Opole"]},
    {"n":"Urząd Skarbowy w Prudniku","w":"opolskie","p":["prudnicki"]},
    {"n":"Urząd Skarbowy w Strzelcach Opolskich","w":"opolskie","p":["strzelecki"]},
    {"n":"Urząd Skarbowy w Brzozowie","w":"podkarpackie","p":["brzozowski"]},
    {"n":"Urząd Skarbowy w Dębicy","w":"podkarpackie","p":["dębicki"]},
    {"n":"Urząd Skarbowy w Jarosławiu","w":"podkarpackie","p":["jarosławski"]},
    {"n":"Urząd Skarbowy w Jaśle","w":"podkarpackie","p":["jasielski"]},
    {"n":"Urząd Skarbowy w Kolbuszowej","w":"podkarpackie","p":["kolbuszowski"]},
    {"n":"Urząd Skarbowy w Krośnie","w":"podkarpackie","p":["krośnieński"],"c":["Krosno"]},
    {"n":"Urząd Skarbowy w Lesku","w":"podkarpackie","p":["leski"]},
    {"n":"Urząd Skarbowy w Leżajsku","w":"podkarpackie","p":["leżajski"]},
    {"n":"Urząd Skarbowy w Lubaczowie","w":"podkarpackie","p":["lubaczowski"]},
    {"n":"Urząd Skarbowy w Łańcucie","w":"podkarpackie","p":["łańcucki"]},
    {"n":"Urząd Skarbowy w Mielcu","w":"podkarpackie","p":["mielecki"]},
    {"n":"Urząd Skarbowy w Nisku","w":"podkarpackie","p":["niżański"]},
    {"n":"Urząd Skarbowy w Przemyślu","w":"podkarpackie","p":["przemyski"],"c":["Przemyśl"]},
    {"n":"Urząd Skarbowy w Przeworsku","w":"podkarpackie","p":["przeworski"]},
    {"n":"Urząd Skarbowy w Ropczycach","w":"podkarpackie","p":["ropczycko-sędziszowski"]},
    {"n":"Pierwszy Urząd Skarbowy w Rzeszowie","w":"podkarpackie","g":{"rzeszowski":["Dynów","Błażowa","Chmielnik","Hyżne","Lubenia","Tyczyn"]},"c":["Rzeszów"]},
    {"n":"Drugi Urząd Skarbowy w Rzeszowie","w":"podkarpackie","g":{"rzeszowski":["Boguchwała","Głogów Małopolski","Kamień","Krasne","Sokołów Małopolski","Świlcza","Trzebownisko"]},"c":["Rzeszów"]},
    {"n":"Urząd Skarbowy w Sanoku","w":"podkarpackie","p":["sanocki"]},
    {"n":"Urząd Skarbowy w Stalowej Woli","w":"podkarpackie","p":["stalowowolski"]},
    {"n":"Urząd Skarbowy w Strzyżowie","w":"podkarpackie","p":["strzyżowski"]},
    {"n":"Urząd Skarbowy w Tarnobrzegu","w":"podkarpackie","p":["tarnobrzeski"],"c":["Tarnobrzeg"]},
    {"n":"Urząd Skarbowy w Ustrzykach Dolnych","w":"podkarpackie","p":["bieszczadzki"]},
    {"n":"Urząd Skarbowy w Augustowie","w":"podlaskie","p":["augustowski"]},
    {"n":"Pierwszy Urząd Skarbowy w Białymstoku","w":"podlaskie","c":["Białystok"]},
    {"n":"Drugi Urząd Skarbowy w Białymstoku","w":"podlaskie","p":["białostocki"],"c":["Białystok"]},
    {"n":"Urząd Skarbowy w Bielsku Podlaskim","w":"podlaskie","p":["bielski"]},
    {"n":"Urząd Skarbowy w Grajewie","w":"podlaskie","p":["grajewski"]},
    {"n":"Urząd Skarbowy w Hajnówce","w":"podlaskie","p":["hajnowski"]},
    {"n":"Urząd Skarbowy w Kolnie","w":"podlaskie","p":["kolneński"]},
    {"n":"Urząd Skarbowy w Łomży","w":"podlaskie","p":["łomżyński"],"c":["Łomża"]},
    {"n":"Urząd Skarbowy w Mońkach","w":"podlaskie","p":["moniecki"]},
    {"n":"Urząd Skarbowy w Siemiatyczach","w":"podlaskie","p":["siemiatycki"]},
    {"n":"Urząd Skarbowy w Sokółce","w":"podlaskie","p":["sokolski"]},
    {"n":"Urząd Skarbowy w Suwałkach","w":"podlaskie","p":["suwalski","sejneński"],"c":["Suwałki"]},
    {"n":"Urząd Skarbowy w Wysokiem Mazowieckiem","w":"podlaskie","p":["wysokomazowiecki"]},
    {"n":"Urząd Skarbowy w Zambrowie","w":"podlaskie","p":["zambrowski"]},
    {"n":"Urząd Skarbowy w Bytowie","w":"pomorskie","p":["bytowski"]},
    {"n":"Urząd Skarbowy w Chojnicach","w":"pomorskie","p":["chojnicki"]},
    {"n":"Urząd Skarbowy w Człuchowie","w":"pomorskie","p":["człuchowski"]},
    {"n":"Pierwszy Urząd Skarbowy w Gdańsku","w":"pomorskie","c":["Gdańsk"]},
    {"n":"Drugi Urząd Skarbowy w Gdańsku","w":"pomorskie","c":["Gdańsk"]},
    {"n":"Trzeci Urząd Skarbowy w Gdańsku","w":"pomorskie","c":["Gdańsk"]},
    {"n":"Pierwszy Urząd Skarbowy w Gdyni","w":"pomorskie","c":["Gdynia"]},
    {"n":"Drugi Urząd Skarbowy w Gdyni","w":"pomorskie","c":["Gdynia"]},
    {"n":"Urząd Skarbowy w Kartuzach","w":"pomorskie","p":["kartuski"]},
    {"n":"Urząd Skarbowy w Kościerzynie","w":"pomorskie","p":["kościerski"]},
    {"n":"Urząd Skarbowy w Kwidzynie","w":"pomorskie","p":["kwidzyński"]},
    {"n":"Urząd Skarbowy w Lęborku","w":"pomorskie","p":["lęborski"]},
    {"n":"Urząd Skarbowy w Malborku","w":"pomorskie","p":["malborski","nowodworski","sztumski"]},
    {"n":"Urząd Skarbowy w Pucku","w":"pomorskie","p":["pucki"]},
    {"n":"Urząd Skarbowy w Słupsku","w":"pomorskie","p":["słupski"],"c":["Słupsk"]},
    {"n":"Urząd Skarbowy w Sopocie","w":"pomorskie","c":["Sopot"]},
    {"n":"Urząd Skarbowy w Starogardzie Gdańskim","w":"pomorskie","p":["starogardzki"]},
    {"n":"Urząd Skarbowy w Tczewie","w":"pomorskie","p":["tczewski"]},
    {"n":"Urząd Skarbowy w Pruszczu Gdańskim","w":"pomorskie","p":["gdański"]},
    {"n":"Urząd Skarbowy w Wejherowie","w":"pomorskie","p":["wejherowski"]},
    {"n":"Urząd Skarbowy w Będzinie","w":"śląskie","p":["będziński"]},
    {"n":"Pierwszy Urząd Skarbowy w Bielsku-Białej","w":"śląskie","c":["Bielsko-Biała"]},
    {"n":"Drugi Urząd Skarbowy w Bielsku-Białej","w":"śląskie","g":{"bielski":["Szczyrk","Buczkowice","Jasienica","Jaworze","Kozy","Porąbka","Wilamowice","Wilkowice"]},"c":["Bielsko-Biała"]},
    {"n":"Urząd Skarbowy w Bytomiu","w":"śląskie","c":["Bytom"]},
    {"n":"Urząd Skarbowy w Chorzowie","w":"śląskie","c":["Chorzów","Świętochłowice"]},
    {"n":"Urząd Skarbowy w Cieszynie","w":"śląskie","p":["cieszyński"]},
    {"n":"Urząd Skarbowy w Czechowicach-Dziedzicach","w":"śląskie","g":{"bielski":["Bestwina","Czechowice-Dziedzice"]}},
    {"n":"Pierwszy Urząd Skarbowy w Częstochowie","w":"śląskie","g":{"częstochowski":["Blachownia","Kamienica Polska","Konopiska","Mykanów","Poczesna","Starcza"]},"c":["Częstochowa"]},
    {"n":"Drugi Urząd Skarbowy w Częstochowie","w":"śląskie","g":{"częstochowski":["Dąbrowa Zielona","Janów","Kłomnice","Koniecpol","Kruszyna","Lelów","Mstów","Olsztyn","Przyrów","Rędziny"]},"c":["Częstochowa"]},
    {"n":"Urząd Skarbowy w Dąbrowie Górniczej","w":"śląskie","c":["Dąbrowa Górnicza"]},
    {"n":"Pierwszy Urząd Skarbowy w Gliwicach","w":"śląskie","c":["Gliwice"]},
    {"n":"Drugi Urząd Skarbowy w Gliwicach","w":"śląskie","p":["gliwicki"],"c":["Gliwice"]},
    {"n":"Urząd Skarbowy w Jastrzębiu-Zdroju","w":"śląskie","c":["Jastrzębie-Zdrój"]},
    {"n":"Urząd Skarbowy w Jaworznie","w":"śląskie","c":["Jaworzno"]},
    {"n":"Pierwszy Urząd Skarbowy w Katowicach","w":"śląskie","c":["Katowice"]},
    {"n":"Drugi Urząd Skarbowy w Katowicach","w":"śląskie","c":["Katowice"]},
    {"n":"Urząd Skarbowy w Kłobucku","w":"śląskie","p":["kłobucki"]},
    {"n":"Urząd Skarbowy w Lublińcu","w":"śląskie","p":["lubliniecki"]},
    {"n":"Urząd Skarbowy w Mikołowie","w":"śląskie","p":["mikołowski"]},
    {"n":"Urząd Skarbowy w Mysłowicach","w":"śląskie","c":["Mysłowice"]},
    {"n":"Urząd Skarbowy w Myszkowie","w":"śląskie","p":["myszkowski"]},
    {"n":"Urząd Skarbowy w Piekarach Śląskich","w":"śląskie","c":["Piekary Śląskie"]},
    {"n":"Urząd Skarbowy w Pszczynie","w":"śląskie","p":["pszczyński"]},
    {"n":"Urząd Skarbowy w Raciborzu","w":"śląskie","p":["raciborski"]},
    {"n":"Urząd Skarbowy w Rudzie Śląskiej","w":"śląskie","c":["Ruda Śląska"]},
    {"n":"Urząd Skarbowy w Rybniku","w":"śląskie","p":["rybnicki"],"c":["Rybnik"]},
    {"n":"Urząd Skarbowy w Siemianowicach Śląskich","w":"śląskie","c":["Siemianowice Śląskie"]},
    {"n":"Urząd Skarbowy w Sosnowcu","w":"śląskie","c":["Sosnowiec"]},
    {"n":"Urząd Skarbowy w Tarnowskich Górach","w":"śląskie","p":["tarnogórski"]},
    {"n":"Urząd Skarbowy w Tychach","w":"śląskie","p":["bieruńsko-lędziński"],"c":["Tychy"]},
    {"n":"Urząd Skarbowy w Wodzisławiu Śląskim","w":"śląskie","p":["wodzisławski"]},
    {"n":"Urząd Skarbowy w Zabrzu","w":"śląskie","c":["Zabrze"]},
    {"n":"Urząd Skarbowy w Zawierciu","w":"śląskie","p":["zawierciański"]},
    {"n":"Urząd Skarbowy w Żorach","w":"śląskie","c":["Żory"]},
    {"n":"Urząd Skarbowy w Żywcu","w":"śląskie","p":["żywiecki"]},
    {"n":"Urząd Skarbowy w Busku-Zdroju","w":"świętokrzyskie","p":["buski"]},
    {"n":"Urząd Skarbowy w Jędrzejowie","w":"świętokrzyskie","p":["jędrzejowski"]},
    {"n":"Urząd Skarbowy w Kazimierzy Wielkiej","w":"świętokrzyskie","p":["kazimierski"]},
    {"n":"Pierwszy Urząd Skarbowy w Kielcach","w":"świętokrzyskie","g":{"kielecki":["Bieliny","Bodzentyn","Chmielnik","Daleszyce","Górno","Łagów","Masłów","Morawica","Nowa Słupia","Pierzchnica","Raków"]},"c":["Kielce"]},
    {"n":"Drugi Urząd Skarbowy w Kielcach","w":"świętokrzyskie","g":{"kielecki":["Chęciny","Łopuszno","Miedziana Góra","Mniów","Piekoszów","Nowiny","Strawczyn","Zagnańsk"]},"c":["Kielce"]},
    {"n":"Urząd Skarbowy w Końskich","w":"świętokrzyskie","p":["konecki"]},
    {"n":"Urząd Skarbowy w Opatowie","w":"świętokrzyskie","p":["opatowski"]},
    {"n":"Urząd Skarbowy w Ostrowcu Świętokrzyskim","w":"świętokrzyskie","p":["ostrowiecki"]},
    {"n":"Urząd Skarbowy w Pińczowie","w":"świętokrzyskie","p":["pińczowski"]},
    {"n":"Urząd Skarbowy w Sandomierzu","w":"świętokrzyskie","p":["sandomierski"]},
    {"n":"Urząd Skarbowy w Skarżysku-Kamiennej","w":"świętokrzyskie","p":["skarżyski"]},
    {"n":"Urząd Skarbowy w Starachowicach","w":"świętokrzyskie","p":["starachowicki"]},
    {"n":"Urząd Skarbowy w Staszowie","w":"świętokrzyskie","p":["staszowski"]},
    {"n":"Urząd Skarbowy we Włoszczowie","w":"świętokrzyskie","p":["włoszczowski"]},
    {"n":"Urząd Skarbowy w Bartoszycach","w":"warmińsko-mazurskie","p":["bartoszycki","lidzbarski"]},
    {"n":"Urząd Skarbowy w Braniewie","w":"warmińsko-mazurskie","p":["braniewski"]},
    {"n":"Urząd Skarbowy w Działdowie","w":"warmińsko-mazurskie","p":["działdowski"]},
    {"n":"Urząd Skarbowy w Elblągu","w":"warmińsko-mazurskie","p":["elbląski"],"c":["Elbląg"]},
    {"n":"Urząd Skarbowy w Ełku","w":"warmińsko-mazurskie","p":["ełcki"]},
    {"n":"Urząd Skarbowy w Giżycku","w":"warmińsko-mazurskie","p":["giżycki","węgorzewski"]},
    {"n":"Urząd Skarbowy w Iławie","w":"warmińsko-mazurskie","p":["iławski"]},
    {"n":"Urząd Skarbowy w Kętrzynie","w":"warmińsko-mazurskie","p":["kętrzyński","mrągowski"]},
    {"n":"Urząd Skarbowy w Nidzicy","w":"warmińsko-mazurskie","p":["nidzicki"]},
    {"n":"Urząd Skarbowy w Nowym Mieście Lubawskim","w":"warmińsko-mazurskie","p":["nowomiejski"]},
    {"n":"Urząd Skarbowy w Olecku","w":"warmińsko-mazurskie","p":["olecki","gołdapski"]},
    {"n":"Urząd Skarbowy w Olsztynie","w":"warmińsko-mazurskie","p":["olsztyński"],"c":["Olsztyn"]},
    {"n":"Urząd Skarbowy w Ostródzie","w":"warmińsko-mazurskie","p":["ostródzki"]},
    {"n":"Urząd Skarbowy w Piszu","w":"warmińsko-mazurskie","p":["piski"]},
    {"n":"Urząd Skarbowy w Szczytnie","w":"warmińsko-mazurskie","p":["szczycieński"]},
    {"n":"Urząd Skarbowy w Czarnkowie","w":"wielkopolskie","p":["czarnkowsko-trzcianecki"]},
    {"n":"Urząd Skarbowy w Gnieźnie","w":"wielkopolskie","p":["gnieźnieński"]},
    {"n":"Urząd Skarbowy w Gostyniu","w":"wielkopolskie","p":["gostyński"]},
    {"n":"Urząd Skarbowy w Grodzisku Wielkopolskim","w":"wielkopolskie","p":["grodziski"]},
    {"n":"Urząd Skarbowy w Jarocinie","w":"wielkopolskie","p":["jarociński"]},
    {"n":"Urząd Skarbowy w Pleszewie","w":"wielkopolskie","p":["pleszewski"]},
    {"n":"Pierwszy Urząd Skarbowy w Kaliszu","w":"wielkopolskie","c":["Kalisz"]},
    {"n":"Drugi Urząd Skarbowy w Kaliszu","w":"wielkopolskie","p":["kaliski"]},
    {"n":"Urząd Skarbowy w Kępnie","w":"wielkopolskie","p":["kępiński"]},
    {"n":"Urząd Skarbowy w Kole","w":"wielkopolskie","p":["kolski"]},
    {"n":"Urząd Skarbowy w Koninie","w":"wielkopolskie","p":["koniński"],"c":["Konin"]},
    {"n":"Urząd Skarbowy w Kościanie","w":"wielkopolskie","p":["kościański"]},
    {"n":"Urząd Skarbowy w Krotoszynie","w":"wielkopolskie","p":["krotoszyński"]},
    {"n":"Urząd Skarbowy w Lesznie","w":"wielkopolskie","p":["leszczyński"],"c":["Leszno"]},
    {"n":"Urząd Skarbowy w Międzychodzie","w":"wielkopolskie","p":["międzychodzki"]},
    {"n":"Urząd Skarbowy w Nowym Tomyślu","w":"wielkopolskie","p":["nowotomyski"]},
    {"n":"Urząd Skarbowy w Ostrowie Wielkopolskim","w":"wielkopolskie","p":["ostrowski"]},
    {"n":"Urząd Skarbowy w Ostrzeszowie","w":"wielkopolskie","p":["ostrzeszowski"]},
    {"n":"Urząd Skarbowy w Pile","w":"wielkopolskie","p":["pilski"]},
    {"n":"Urząd Skarbowy w Chodzieży","w":"wielkopolskie","p":["chodzieski"]},
    {"n":"Urząd Skarbowy Poznań-Grunwald","w":"wielkopolskie","c":["Poznań"],"d":["Grunwald"]},
    {"n":"Urząd Skarbowy Poznań-Jeżyce","w":"wielkopolskie","g":{"poznański":["Rokietnica","Tarnowo Podgórne"]},"c":["Poznań"],"d":["Jeżyce"]},
    {"n":"Urząd Skarbowy Poznań-Nowe Miasto","w":"wielkopolskie","c":["Poznań"],"d":["Nowe Miasto"]},
    {"n":"Pierwszy Urząd Skarbowy w Poznaniu","w":"wielkopolskie","g":{"poznański":["Buk","Czerwonak","Dopiewo","Kleszczewo","Komorniki","Kostrzyn","Kórnik","Mosina","Murowana Goślina","Pobiedziska","Stęszew","Swarzędz"]}},
    {"n":"Urząd Skarbowy Poznań-Wilda","w":"wielkopolskie","g":{"poznański":["Luboń","Puszczykowo"]},"c":["Poznań"],"d":["Wilda","Stare Miasto"]},
    {"n":"Urząd Skarbowy Poznań-Winogrady","w":"wielkopolskie","g":{"poznański":["Suchy Las"]},"c":["Poznań"],"d":["Winogrady","Piątkowo","Radojewo","Umultowo","Morasko","Naramowice","Stare Miasto"]},
    {"n":"Urząd Skarbowy w Rawiczu","w":"wielkopolskie","p":["rawicki"]},
    {"n":"Urząd Skarbowy w Słupcy","w":"wielkopolskie","p":["słupecki"]},
    {"n":"Urząd Skarbowy w Szamotułach","w":"wielkopolskie","p":["szamotulski"]},
    {"n":"Urząd Skarbowy w Śremie","w":"wielkopolskie","p":["śremski"]},
    {"n":"Urząd Skarbowy w Środzie Wielkopolskiej","w":"wielkopolskie","p":["średzki"]},
    {"n":"Urząd Skarbowy w Turku","w":"wielkopolskie","p":["turecki"]},
    {"n":"Urząd Skarbowy w Wągrowcu","w":"wielkopolskie","p":["wągrowiecki"]},
    {"n":"Urząd Skarbowy w Obornikach","w":"wielkopolskie","p":["obornicki"]},
    {"n":"Urząd Skarbowy w Wolsztynie","w":"wielkopolskie","p":["wolsztyński"]},
    {"n":"Urząd Skarbowy we Wrześni","w":"wielkopolskie","p":["wrzesiński"]},
    {"n":"Urząd Skarbowy w Złotowie","w":"wielkopolskie","p":["złotowski"]},
    {"n":"Urząd Skarbowy w Białogardzie","w":"zachodniopomorskie","p":["białogardzki","świdwiński"]},
    {"n":"Urząd Skarbowy w Choszcznie","w":"zachodniopomorskie","p":["choszczeński"]},
    {"n":"Urząd Skarbowy w Drawsku Pomorskim","w":"zachodniopomorskie","p":["drawski","łobeski"]},
    {"n":"Urząd Skarbowy w Goleniowie","w":"zachodniopomorskie","p":["goleniowski"]},
    {"n":"Urząd Skarbowy w Gryficach","w":"zachodniopomorskie","p":["gryficki"]},
    {"n":"Urząd Skarbowy w Gryfinie","w":"zachodniopomorskie","p":["gryfiński"]},
    {"n":"Urząd Skarbowy w Kamieniu Pomorskim","w":"zachodniopomorskie","p":["kamieński"]},
    {"n":"Urząd Skarbowy w Kołobrzegu","w":"zachodniopomorskie","p":["kołobrzeski"]},
    {"n":"Pierwszy Urząd Skarbowy w Koszalinie","w":"zachodniopomorskie","c":["Koszalin"]},
    {"n":"Drugi Urząd Skarbowy w Koszalinie","w":"zachodniopomorskie","p":["koszaliński","sławieński"]},
    {"n":"Urząd Skarbowy w Myśliborzu","w":"zachodniopomorskie","p":["myśliborski"]},
    {"n":"Urząd Skarbowy w Pyrzycach","w":"zachodniopomorskie","p":["pyrzycki"]},
    {"n":"Urząd Skarbowy w Stargardzie","w":"zachodniopomorskie","p":["stargardzki"]},
    {"n":"Pierwszy Urząd Skarbowy w Szczecinie","w":"zachodniopomorskie","p":["policki"],"c":["Szczecin"]},
    {"n":"Drugi Urząd Skarbowy w Szczecinie","w":"zachodniopomorskie","c":["Szczecin"]},
    {"n":"Trzeci Urząd Skarbowy w Szczecinie","w":"zachodniopomorskie","c":["Szczecin"]},
    {"n":"Urząd Skarbowy w Szczecinku","w":"zachodniopomorskie","p":["szczecinecki"]},
    {"n":"Urząd Skarbowy w Świnoujściu","w":"zachodniopomorskie","c":["Świnoujście"]},
    {"n":"Urząd Skarbowy w Wałczu","w":"zachodniopomorskie","p":["wałecki"]}];

  function norm(s) { return (s || '').toString().trim().toLowerCase(); }
  function has(list, v) { return (list || []).some(function (x) { return norm(x) === v; }); }

  // offices competent for one place (województwo + powiat + gmina, lower-cased)
  function officesFor(woj, powiat, gmina, dzielnica) {
    var inWoj = US.filter(function (o) { return o.w === woj; });
    // miasto na prawach powiatu: the API gives the city name as the powiat
    var city = inWoj.filter(function (o) { return has(o.c, powiat) || (!powiat && has(o.c, gmina)); });
    if (city.length) {
      // "Poznań-Grunwald" -> "grunwald": keep the offices whose territory names that district
      var dz = norm(dzielnica).replace(/^.*?-/, '');
      var named = dz ? city.filter(function (o) { return has(o.d, dz); }) : [];
      return named.length ? named : city;
    }
    return inWoj.filter(function (o) {
      if (has(o.p, powiat)) return true;
      return Object.keys(o.g || {}).some(function (p) { return p === powiat && has(o.g[p], gmina); });
    });
  }

  var cache = {};
  function fetchKod(kod) {
    if (!cache[kod]) {
      cache[kod] = fetch(API + kod, { headers: { Accept: 'application/json' } })
        .then(function (r) { return r.ok ? r.json() : []; })
        .then(function (d) { return Array.isArray(d) ? d : []; })
        .catch(function () { delete cache[kod]; return []; });
    }
    return cache[kod];
  }
  function uniq(a) { return a.filter(function (x, i) { return x && a.indexOf(x) === i; }); }

  // -> { wojewodztwo, powiat, gmina, nfz, us: [nazwy] }; pola puste gdy niejednoznaczne.
  async function lookup(kod, miejscowosc, ulica) {
    var m = (kod || '').replace(/\D/g, '');
    if (m.length !== 5) return null;
    var rows = await fetchKod(m.slice(0, 2) + '-' + m.slice(2));
    if (!rows.length) return null;
    // one code can span several localities — narrow down by the typed one
    var mi = norm(miejscowosc);
    var same = rows.filter(function (r) { return mi && norm(r.miejscowosc) === mi; });
    if (same.length) rows = same;
    // ...and by the typed street, which pins down the district in big cities
    var ul = norm(ulica).replace(/^(ul\.|ulica|al\.|aleja|os\.|pl\.)\s*/, '');
    var street = rows.filter(function (r) { return ul && r.ulica && norm(r.ulica) === ul; });
    if (street.length) rows = street;

    var us = [], woj = [], pow = [], gm = [];
    rows.forEach(function (r) {
      var w = norm(r.wojewodztwo), p = norm(r.powiat), g = norm(r.gmina || r.miejscowosc);
      if (w) woj.push(w);
      if (r.powiat) pow.push(r.powiat);
      if (r.gmina) gm.push(r.gmina);
      if (!w || (!p && !g)) return;
      officesFor(w, p, g, r.dzielnica).forEach(function (o) { us.push(o.n); });
    });
    woj = uniq(woj); pow = uniq(pow); gm = uniq(gm);
    return {
      wojewodztwo: woj.length === 1 ? woj[0] : '',
      powiat: pow.length === 1 ? pow[0] : '',
      gmina: gm.length === 1 ? gm[0] : '',
      nfz: woj.length === 1 ? (NFZ[woj[0]] || '') : '',
      us: uniq(us),
    };
  }

  window.Urzedy = { lookup: lookup };
})();
