-- PROPOZYCJA — NIE URUCHAMIAĆ bez decyzji orkiestratora.
-- Reguły bazy wiedzy (portal_wiedza) dla generatora pojedynczych dokumentów kadrowych.
-- Każda reguła została przeczytana w tekście jednolitym aktu (rejestr ELI) w dniu 2026-10-09.
-- Format jak w supabase/migrations/portal_wiedza_seed.sql; kolumna eli = akt pierwotny,
-- który śledzi prawo-monitor.

insert into public.portal_prawo_akty (eli, tytul, skrot) values
  ('DU/1964/93', 'Kodeks cywilny', 'Kodeks cywilny'),
  ('DU/1960/168', 'Kodeks postępowania administracyjnego', 'KPA'),
  ('DU/2006/1635', 'Ustawa o opłacie skarbowej', 'Ustawa o opłacie skarbowej'),
  ('DU/1991/234', 'Ustawa o związkach zawodowych', 'Ustawa o związkach zawodowych'),
  ('DU/2003/844', 'Ustawa o szczególnych zasadach rozwiązywania z pracownikami stosunków pracy z przyczyn niedotyczących pracowników', 'Ustawa o zwolnieniach grupowych'),
  ('DU/2016/2292', 'Rozporządzenie w sprawie świadectwa pracy', 'Rozp. — świadectwo pracy'),
  ('DU/2018/2369', 'Rozporządzenie w sprawie dokumentacji pracowniczej', 'Rozp. — dokumentacja pracownicza'),
  ('DU/1996/332', 'Rozporządzenie w sprawie przeprowadzania badań lekarskich pracowników', 'Rozp. — badania lekarskie'),
  ('DU/2004/1860', 'Rozporządzenie w sprawie szkolenia w dziedzinie bezpieczeństwa i higieny pracy', 'Rozp. — szkolenia BHP'),
  ('DU/2025/322', 'Rozporządzenie w sprawie wniosków dotyczących uprawnień pracowników związanych z rodzicielstwem', 'Rozp. — wnioski rodzicielskie'),
  ('DU/1996/281', 'Rozporządzenie w sprawie sposobu usprawiedliwiania nieobecności w pracy oraz udzielania pracownikom zwolnień od pracy', 'Rozp. — usprawiedliwianie nieobecności'),
  ('DU/2019/1102', 'Rozporządzenie w sprawie deklaracji o rezygnacji z dokonywania wpłat do PPK', 'Rozp. — rezygnacja z PPK')
on conflict (eli) do nothing;

insert into public.portal_wiedza (id, dzial, temat, tresc, podstawa, eli, zweryfikowano, kolejnosc) values
('dok-wypowiedzenie-wymogi', 'Rozwiązanie umowy', 'Wypowiedzenie przez pracodawcę — trzy obowiązkowe elementy',
 $$Oświadczenie pracodawcy o wypowiedzeniu umowy o pracę musi być złożone na piśmie, zawierać przyczynę (przy umowie na czas nieokreślony i — w obecnym brzmieniu przepisu — także na czas określony; przy okresie próbnym przyczyny się nie podaje) oraz pouczenie o prawie odwołania do sądu pracy. Odwołanie wnosi się w ciągu 21 dni od doręczenia pisma. Forma pisemna to podpis własnoręczny albo kwalifikowany podpis elektroniczny — podpis zaufany jej nie daje.$$,
 'art. 30 § 3–5 i art. 264 § 1 Kodeksu pracy', 'DU/1974/141', '2026-10-09', 410),
('dok-okresy-wypowiedzenia', 'Rozwiązanie umowy', 'Okresy wypowiedzenia umowy o pracę',
 $$Okres próbny: 3 dni robocze (okres próbny do 2 tygodni), 1 tydzień (dłuższy niż 2 tygodnie), 2 tygodnie (3 miesiące). Umowa na czas określony i nieokreślony: 2 tygodnie przy zatrudnieniu krótszym niż 6 miesięcy, 1 miesiąc przy co najmniej 6 miesiącach, 3 miesiące przy co najmniej 3 latach u danego pracodawcy. Okres liczony w tygodniach kończy się w sobotę, a w miesiącach — w ostatnim dniu miesiąca.$$,
 'art. 30 § 2¹, art. 34 i art. 36 § 1 Kodeksu pracy', 'DU/1974/141', '2026-10-09', 420),
('dok-wypowiedzenie-zakazy', 'Rozwiązanie umowy', 'Kiedy nie wolno wypowiedzieć umowy i konsultacja ze związkiem',
 $$Pracodawca nie może wypowiedzieć umowy w czasie urlopu pracownika ani innej usprawiedliwionej nieobecności, jeżeli nie upłynął jeszcze okres uprawniający do rozwiązania umowy bez wypowiedzenia, ani pracownikowi, któremu brakuje nie więcej niż 4 lata do wieku emerytalnego. O zamiarze wypowiedzenia umowy na czas określony lub nieokreślony zawiadamia się (papierowo lub elektronicznie) reprezentującą pracownika zakładową organizację związkową, podając przyczynę; organizacja ma 5 dni na zastrzeżenia.$$,
 'art. 38, art. 39 i art. 41 Kodeksu pracy', 'DU/1974/141', '2026-10-09', 430),
('dok-rozwiazanie-art52', 'Rozwiązanie umowy', 'Rozwiązanie bez wypowiedzenia z winy pracownika — miesiąc na decyzję',
 $$Rozwiązanie umowy bez wypowiedzenia z winy pracownika nie może nastąpić po upływie 1 miesiąca od uzyskania przez pracodawcę wiadomości o okoliczności uzasadniającej rozwiązanie. Pismo musi wskazywać przyczynę i zawierać pouczenie o prawie wniesienia do sądu pracy żądania przywrócenia do pracy lub odszkodowania w ciągu 21 dni od doręczenia. Zakładowa organizacja związkowa wyraża opinię najpóźniej w ciągu 3 dni.$$,
 'art. 30 § 4–5, art. 52 § 1–3 i art. 264 § 2 Kodeksu pracy', 'DU/1974/141', '2026-10-09', 440),
('dok-wypowiedzenie-zmieniajace', 'Rozwiązanie umowy', 'Wypowiedzenie zmieniające — pouczenie o połowie okresu wypowiedzenia',
 $$Wypowiedzenie warunków pracy lub płacy jest dokonane, gdy pracownikowi zaproponowano na piśmie nowe warunki. Pismo musi zawierać pouczenie, że brak oświadczenia o odmowie przed upływem połowy okresu wypowiedzenia oznacza zgodę na nowe warunki. Bez tego pouczenia pracownik może odmówić aż do końca okresu wypowiedzenia. W razie odmowy umowa rozwiązuje się z upływem okresu wypowiedzenia.$$,
 'art. 42 § 1–3 Kodeksu pracy', 'DU/1974/141', '2026-10-09', 450),
('dok-swiadectwo-pracy', 'Rozwiązanie umowy', 'Świadectwo pracy — termin i informacja o dokumentacji',
 $$Świadectwo pracy wydaje się w dniu ustania stosunku pracy; gdy to obiektywnie niemożliwe — wysyła się je w ciągu 7 dni. Wydania nie wolno uzależniać od rozliczenia się pracownika. Razem ze świadectwem pracodawca wydaje informację o okresie przechowywania dokumentacji pracowniczej, możliwości jej odbioru do końca miesiąca następującego po upływie tego okresu oraz o zniszczeniu dokumentacji w razie nieodebrania. Pracownik ma 14 dni na wniosek o sprostowanie świadectwa, a po odmowie — 14 dni na wystąpienie do sądu pracy.$$,
 'art. 94⁶ i art. 97 § 1–2¹ Kodeksu pracy; rozporządzenie w sprawie świadectwa pracy', 'DU/1974/141', '2026-10-09', 460),
('dok-kara-porzadkowa', 'Umowa o pracę', 'Kara porządkowa — terminy, wysłuchanie, sprzeciw',
 $$Kary są tylko trzy: upomnienie, nagana i kara pieniężna (ta ostatnia wyłącznie za naruszenie przepisów BHP lub przeciwpożarowych, opuszczenie pracy bez usprawiedliwienia, nietrzeźwość lub alkohol w pracy). Kary nie można zastosować po upływie 2 tygodni od powzięcia wiadomości o naruszeniu ani po 3 miesiącach od naruszenia; przedtem trzeba pracownika wysłuchać. Zawiadomienie na piśmie wskazuje rodzaj i datę naruszenia oraz informuje o prawie sprzeciwu w ciągu 7 dni. Nieodrzucenie sprzeciwu w ciągu 14 dni oznacza jego uwzględnienie.$$,
 'art. 108–112 Kodeksu pracy', 'DU/1974/141', '2026-10-09', 470),
('dok-aneks-forma', 'Umowa o pracę', 'Zmiana warunków umowy o pracę — forma pisemna',
 $$Zmiana warunków umowy o pracę wymaga formy pisemnej (aneks podpisany przez obie strony). Wyjątek: uzgodnienie pracy zdalnej w trakcie zatrudnienia — tu formy pisemnej się nie stosuje. O zmianie warunków zatrudnienia objętych informacją z art. 29 § 3 pracodawca informuje najpóźniej w dniu, w którym zmiana ma zastosowanie.$$,
 'art. 29 § 3³ i § 4, art. 67¹⁹ § 2 Kodeksu pracy', 'DU/1974/141', '2026-10-09', 480),
('dok-postac-elektroniczna-2026', 'Umowa o pracę', 'Wnioski pracownicze — postać papierowa lub elektroniczna (zmiana 2026)',
 $$Od 27 stycznia 2026 r. kolejne wnioski i informacje można składać w postaci elektronicznej, m.in.: wniosek o indywidualny rozkład czasu pracy, wniosek o urlop bezpłatny, wniosek o czas wolny za nadgodziny, potwierdzenie zapoznania się z przepisami BHP, informacja o monitoringu, zawiadomienie związku o zamiarze wypowiedzenia. „Postać papierowa lub elektroniczna” nie jest formą pisemną — wystarcza e-mail lub system kadrowy. Formy pisemnej nadal wymagają: umowa o pracę i jej zmiana, wypowiedzenie i rozwiązanie bez wypowiedzenia, zakaz konkurencji, zawiadomienie o karze porządkowej, zgoda na potrącenie.$$,
 'art. 22² § 8, art. 38 § 1–2, art. 142, art. 151² § 1, art. 174 § 1, art. 237⁴ § 3 Kodeksu pracy (zmiana: Dz. U. z 2026 r. poz. 25)', 'DU/1974/141', '2026-10-09', 490),
('dok-praca-zdalna', 'Umowa o pracę', 'Praca zdalna — co musi być w dokumentach',
 $$Zasady pracy zdalnej określa porozumienie ze związkami albo regulamin; gdy ich nie ma — porozumienie z pracownikiem. Pracodawca zapewnia narzędzia oraz pokrywa koszty energii i telekomunikacji (albo wypłaca ekwiwalent lub ryczałt). Przed dopuszczeniem pracownik potwierdza zapoznanie się z oceną ryzyka i informacją BHP, oświadcza, że na stanowisku pracy zdalnej są bezpieczne i higieniczne warunki, i potwierdza zapoznanie się z procedurami ochrony danych. Praca zdalna okazjonalna: na wniosek pracownika, do 24 dni w roku kalendarzowym.$$,
 'art. 67¹⁹–67²⁰, art. 67²⁴, art. 67²⁶, art. 67³¹ § 5–7 i art. 67³³ Kodeksu pracy', 'DU/1974/141', '2026-10-09', 500),
('dok-zakaz-konkurencji', 'Umowa o pracę', 'Zakaz konkurencji — forma i odszkodowanie',
 $$Umowa o zakazie konkurencji (w trakcie i po ustaniu zatrudnienia) wymaga formy pisemnej pod rygorem nieważności. Zakaz po ustaniu stosunku pracy można zawrzeć tylko z pracownikiem mającym dostęp do szczególnie ważnych informacji; umowa musi określać okres zakazu i odszkodowanie nie niższe niż 25% wynagrodzenia otrzymanego przed ustaniem stosunku pracy przez okres odpowiadający okresowi zakazu. Poza umową o zakazie konkurencji pracodawca nie może zakazać pracownikowi dodatkowego zatrudnienia.$$,
 'art. 26¹ i art. 101¹–101³ Kodeksu pracy', 'DU/1974/141', '2026-10-09', 510),
('dok-potracenia-zgoda', 'Wynagrodzenie', 'Potrącenia za zgodą pracownika',
 $$Należności inne niż wymienione w art. 87 § 1 i 7 Kodeksu pracy można potrącić z wynagrodzenia tylko za zgodą pracownika wyrażoną na piśmie, z zachowaniem kwoty wolnej (przy należnościach na rzecz pracodawcy — minimalne wynagrodzenie po odliczeniu składek, zaliczki na podatek i wpłat do PPK). Pracownik nie może zrzec się prawa do wynagrodzenia. Czynszu za kwaterę cudzoziemca zatrudnionego przy pracy sezonowej nie wolno potrącać z wynagrodzenia — takie postanowienia są nieważne.$$,
 'art. 84, art. 87¹ § 1 pkt 1 i art. 91 Kodeksu pracy; art. 59 ust. 2 ustawy o powierzaniu pracy cudzoziemcom', 'DU/1974/141', '2026-10-09', 520),
('dok-urlop-opiekunczy-sila-wyzsza', 'Urlopy', 'Urlop opiekuńczy i zwolnienie z powodu siły wyższej',
 $$Urlop opiekuńczy: 5 dni w roku, wniosek co najmniej 1 dzień wcześniej; wniosek wskazuje imię i nazwisko osoby wymagającej opieki, przyczynę oraz stopień pokrewieństwa (syn, córka, matka, ojciec, małżonek) albo adres osoby mieszkającej w tym samym gospodarstwie domowym. Zwolnienie z powodu siły wyższej: 2 dni albo 16 godzin w roku, wniosek najpóźniej w dniu zwolnienia, pracodawca musi go uwzględnić, przysługuje połowa wynagrodzenia. Oba uprawnienia wykazuje się w świadectwie pracy.$$,
 'art. 148¹ i art. 173¹ Kodeksu pracy', 'DU/1974/141', '2026-10-09', 530),
('dok-wnioski-rodzicielskie', 'Urlopy', 'Wnioski rodzicielskie — nowe rozporządzenie i zagraniczny akt urodzenia',
 $$Treść wniosków o urlop rodzicielski, ojcowski i wychowawczy oraz listę załączników określa rozporządzenie z 11 marca 2025 r. (obowiązuje od 19 marca 2025 r.; rozporządzenie z 2023 r. jest uchylone). Terminy: urlop rodzicielski i wychowawczy — wniosek co najmniej 21 dni wcześniej, ojcowski — 7 dni. Zagraniczny dokument potwierdzający urodzenie dziecka dołącza się z tłumaczeniem na polski, chyba że wydano go w UE, EFTA/EOG, Szwajcarii albo w państwie mającym z Polską umowę o zabezpieczeniu społecznym, w języku urzędowym tego państwa. Dokumentów będących już w aktach osobowych nie dołącza się.$$,
 '§ 15, § 17, § 19, § 21–22 rozporządzenia MRPiPS z 11.03.2025 r.; art. 182¹d, art. 182³ i art. 186 Kodeksu pracy', 'DU/2025/322', '2026-10-09', 540),
('dok-skierowanie-badania', 'BHP', 'Skierowanie na badania lekarskie — wzór urzędowy, dwa egzemplarze',
 $$Badania wstępne, okresowe i kontrolne przeprowadza się na podstawie skierowania wydanego przez pracodawcę według wzoru z załącznika nr 3a do rozporządzenia; skierowanie wydaje się w dwóch egzemplarzach, jeden dla osoby kierowanej. Musi zawierać rodzaj badania, stanowisko oraz opis warunków pracy z czynnikami szkodliwymi i uciążliwymi i wielkością narażenia. Pracodawca przechowuje skierowania i orzeczenia. Badania kontrolne — po chorobie trwającej dłużej niż 30 dni.$$,
 'art. 229 § 2, 4a i 7 Kodeksu pracy; § 4 rozporządzenia w sprawie badań lekarskich pracowników', 'DU/1996/332', '2026-10-09', 550),
('dok-karta-szkolenia-bhp', 'BHP', 'Karta szkolenia wstępnego BHP — także potwierdzenie elektroniczne',
 $$Odbycie instruktażu ogólnego i stanowiskowego potwierdza się w karcie szkolenia wstępnego (wzór w załączniku nr 2 do rozporządzenia), przechowywanej w aktach osobowych. Od 12 grudnia 2025 r. potwierdzenie może być elektroniczne — wtedy pracodawca robi adnotację w miejscu podpisu i dołącza dokument elektroniczny albo jego odwzorowanie. Szkolenie wstępne odbywa się przed dopuszczeniem do pracy, w czasie pracy i na koszt pracodawcy.$$,
 '§ 12 rozporządzenia w sprawie szkolenia w dziedzinie bhp (zmiana: Dz. U. z 2025 r. poz. 1640); art. 237³ § 2–3 Kodeksu pracy', 'DU/2004/1860', '2026-10-09', 560),
('dok-ewidencja-czasu-pracy', 'Umowa o pracę', 'Ewidencja czasu pracy — obowiązkowe rubryki',
 $$Ewidencja czasu pracy, prowadzona oddzielnie dla każdego pracownika, zawiera: liczbę przepracowanych godzin oraz godzinę rozpoczęcia i zakończenia pracy, godziny w porze nocnej, godziny nadliczbowe, dni wolne z oznaczeniem tytułu ich udzielenia, dyżury (godziny i miejsce), rodzaj i wymiar zwolnień od pracy oraz innych usprawiedliwionych nieobecności, wymiar nieobecności nieusprawiedliwionych. Do dokumentacji czasu pracy dołącza się m.in. wnioski o zwolnienie z art. 188, urlop opiekuńczy, zwolnienie z powodu siły wyższej i indywidualny rozkład czasu pracy.$$,
 'art. 149 Kodeksu pracy; § 6 pkt 1 rozporządzenia w sprawie dokumentacji pracowniczej', 'DU/2018/2369', '2026-10-09', 570),
('dok-zlecenie-godziny', 'Wynagrodzenie', 'Zlecenie — potwierdzanie liczby godzin i 3 lata przechowywania',
 $$W umowie zlecenia strony określają sposób potwierdzania liczby godzin; gdy tego nie zrobią, zleceniobiorca przedkłada informację o liczbie godzin (pisemnie, elektronicznie lub w formie dokumentowej) przed terminem wypłaty. Zleceniodawca przechowuje te dokumenty 3 lata od dnia wymagalności wynagrodzenia. Wynagrodzenie za każdą godzinę nie może być niższe od minimalnej stawki godzinowej; przy umowach dłuższych niż miesiąc wypłata co najmniej raz w miesiącu. Wypłata poniżej stawki: grzywna od 1000 zł do 30 000 zł.$$,
 'art. 8a–8c i art. 8e ustawy o minimalnym wynagrodzeniu za pracę', 'DU/2002/1679', '2026-10-09', 580),
('dok-zlecenie-wypowiedzenie', 'Rozwiązanie umowy', 'Wypowiedzenie umowy zlecenia',
 $$Każda ze stron może wypowiedzieć zlecenie w każdym czasie; z góry nie można zrzec się wypowiedzenia z ważnych powodów. Zleceniodawca płaci część wynagrodzenia za dotychczasowe czynności; wypowiedzenie bez ważnego powodu rodzi obowiązek naprawienia szkody. Jeżeli umowa została zawarta na piśmie, w formie dokumentowej albo elektronicznej, jej wypowiedzenie wymaga formy dokumentowej, chyba że umowa zastrzega inną formę. Wyrejestrowanie z ZUS — 7 dni.$$,
 'art. 77 § 2 i art. 746 Kodeksu cywilnego; art. 36 ust. 11 ustawy o systemie ubezpieczeń społecznych', 'DU/1964/93', '2026-10-09', 590),
('dok-umowa-o-dzielo-rud', 'ZUS', 'Umowa o dzieło — zgłoszenie RUD w 7 dni',
 $$Płatnik informuje ZUS o zawarciu każdej umowy o dzieło z osobą, z którą nie pozostaje w stosunku pracy, w terminie 7 dni od dnia zawarcia umowy (formularz RUD). Umowa o dzieło to umowa rezultatu — praca powtarzalna pod kierownictwem nie jest dziełem. Cudzoziemcowi także umowę o dzieło trzeba przedstawić na piśmie przed dopuszczeniem do pracy.$$,
 'art. 36 ust. 17 ustawy o systemie ubezpieczeń społecznych; art. 627 Kodeksu cywilnego; art. 5 ust. 1 ustawy o powierzaniu pracy cudzoziemcom', 'DU/1998/887', '2026-10-09', 600),
('cudz-kopia-umowy-przed-praca', 'Cudzoziemcy', 'Kopia umowy do urzędu przed powierzeniem pracy',
 $$Pracodawca, który ma zezwolenie na pracę albo oświadczenie wpisane do ewidencji, przekazuje organowi kopię umowy z cudzoziemcem w języku polskim przez system teleinformatyczny (praca.gov.pl) PRZED powierzeniem pracy. Brak: grzywna od 1000 zł do 3000 zł. Tak samo karane jest nieprzedstawienie cudzoziemcowi treści umowy w wersji dla niego zrozumiałej.$$,
 'art. 17 ust. 1 pkt 2, art. 68 ust. 1 pkt 2 i art. 84 ust. 6 ustawy o powierzaniu pracy cudzoziemcom', 'DU/2025/621', '2026-10-09', 610),
('cudz-zezwolenie-powiadomienia', 'Cudzoziemcy', 'Zezwolenie na pracę — powiadomienia w 7 dni',
 $$Pracodawca powiadamia organ, który wydał zezwolenie na pracę, w ciągu 7 dni (przez praca.gov.pl), jeżeli cudzoziemiec: nie podjął pracy w okresie 2 miesięcy od początkowej daty ważności zezwolenia, przerwał pracę na okres przekraczający 2 miesiące albo zakończył pracę wcześniej niż 2 miesiące przed upływem ważności zezwolenia. Powiadamia się też o zmianie siedziby, nazwy lub formy prawnej pracodawcy, przejściu zakładu pracy i zmianie nazwy stanowiska bez zmiany obowiązków. Brak powiadomienia: grzywna nie niższa niż 500 zł.$$,
 'art. 18–20 i art. 84 ust. 7 ustawy o powierzaniu pracy cudzoziemcom', 'DU/2025/621', '2026-10-09', 620),
('cudz-pobyt-mos', 'Cudzoziemcy', 'Wniosek o pobyt czasowy — tylko elektronicznie (od 27.04.2026)',
 $$Od 27 kwietnia 2026 r. wniosek o zezwolenie na pobyt czasowy cudzoziemiec składa w postaci elektronicznej przez system MOS i sam go podpisuje (kwalifikowanym podpisem elektronicznym lub podpisem zaufanym); wniosek złożony inaczej pozostawia się bez rozpoznania. Załącznik dotyczący pracy wypełnia w MOS pracodawca po otrzymaniu odnośnika e-mail i podpisuje go kwalifikowanym podpisem elektronicznym, podpisem osobistym lub zaufanym. Termin bez zmian: najpóźniej w ostatnim dniu legalnego pobytu.$$,
 'art. 105 ust. 1, art. 106c ust. 1, 3 i 5, art. 106d ust. 3–4 ustawy o cudzoziemcach (zmiana: Dz. U. z 2025 r. poz. 1794)', 'DU/2013/1650', '2026-10-09', 630),
('cudz-pelnomocnictwo-kpa', 'Cudzoziemcy', 'Pełnomocnictwo w sprawach administracyjnych — tylko osoba fizyczna, 17 zł',
 $$Pełnomocnikiem strony w postępowaniu administracyjnym może być wyłącznie osoba fizyczna mająca zdolność do czynności prawnych — wpisuje się konkretnego pracownika biura, nie firmę. Pełnomocnictwo udziela się na piśmie; do akt składa się oryginał lub urzędowo poświadczony odpis. Opłata skarbowa: 17 zł od każdego stosunku pełnomocnictwa; zwolnione m.in. pełnomocnictwo dla małżonka, wstępnego, zstępnego lub rodzeństwa oraz pełnomocnictwo do podpisywania deklaracji podatkowych składanych elektronicznie.$$,
 'art. 32–33 Kodeksu postępowania administracyjnego; załącznik do ustawy o opłacie skarbowej, część IV', 'DU/1960/168', '2026-10-09', 640),
('dok-ppk-rezygnacja', 'Wynagrodzenie', 'PPK — rezygnacja i powrót do wpłat',
 $$Rezygnację z wpłat do PPK składa się pracodawcy w formie pisemnej na urzędowym wzorze deklaracji; pracodawca informuje instytucję finansową w ciągu 7 dni. Wpłat nie dokonuje się od miesiąca złożenia deklaracji. Co 4 lata, od 1 kwietnia, wpłaty są wznawiane, chyba że uczestnik ponownie złoży deklarację. Uczestnik może w każdym czasie złożyć pisemny wniosek o dokonywanie wpłat — wpłaty od następnego miesiąca.$$,
 'art. 23 ust. 2–6 i 10–11 ustawy o pracowniczych planach kapitałowych', 'DU/2018/2215', '2026-10-09', 650),
('dok-zwolnienia-odprawa', 'Rozwiązanie umowy', 'Odprawa przy zwolnieniu z przyczyn niedotyczących pracownika',
 $$Pracodawca zatrudniający co najmniej 20 pracowników, który rozwiązuje stosunek pracy wyłącznie z przyczyn niedotyczących pracownika (wypowiedzenie lub porozumienie stron), wypłaca odprawę: jednomiesięczne wynagrodzenie przy zatrudnieniu krótszym niż 2 lata, dwumiesięczne — od 2 do 8 lat, trzymiesięczne — ponad 8 lat; nie więcej niż 15-krotność minimalnego wynagrodzenia. W świadectwie pracy wskazuje się wtedy art. 1 albo art. 10 tej ustawy.$$,
 'art. 8 i art. 10 ust. 1 ustawy z 13.03.2003 r. o szczególnych zasadach rozwiązywania z pracownikami stosunków pracy z przyczyn niedotyczących pracowników', 'DU/2003/844', '2026-10-09', 660)
on conflict (id) do update set dzial = excluded.dzial, temat = excluded.temat, tresc = excluded.tresc,
  podstawa = excluded.podstawa, eli = excluded.eli, zweryfikowano = excluded.zweryfikowano, kolejnosc = excluded.kolejnosc;
