-- Knowledge base: the legal rules the Kadry module relies on.
-- Every rule below was read in the consolidated text of the act (ELI register) on the
-- date in "zweryfikowano". prawo-monitor marks a rule do_sprawdzenia when its act is amended.

insert into public.portal_prawo_akty (eli, tytul, skrot) values
  ('DU/2025/621', 'Ustawa o warunkach dopuszczalności powierzania pracy cudzoziemcom na terytorium RP', 'Ustawa o powierzaniu pracy cudzoziemcom'),
  ('DU/2026/203', 'Ustawa o wygaszeniu rozwiązań wynikających z ustawy o pomocy obywatelom Ukrainy', 'Ustawa wygaszająca specustawę ukraińską'),
  ('DU/2022/583', 'Ustawa o pomocy obywatelom Ukrainy w związku z konfliktem zbrojnym', 'Specustawa ukraińska'),
  ('DU/2013/1650', 'Ustawa o cudzoziemcach', 'Ustawa o cudzoziemcach'),
  ('DU/1974/141', 'Kodeks pracy', 'Kodeks pracy'),
  ('DU/2002/1679', 'Ustawa o minimalnym wynagrodzeniu za pracę', 'Ustawa o minimalnym wynagrodzeniu'),
  ('DU/1998/887', 'Ustawa o systemie ubezpieczeń społecznych', 'Ustawa o systemie ubezpieczeń społecznych'),
  ('DU/2004/2135', 'Ustawa o świadczeniach opieki zdrowotnej finansowanych ze środków publicznych', 'Ustawa zdrowotna'),
  ('DU/2018/2215', 'Ustawa o pracowniczych planach kapitałowych', 'Ustawa o PPK'),
  ('DU/1991/350', 'Ustawa o podatku dochodowym od osób fizycznych', 'Ustawa o PIT'),
  ('DU/2018/1000', 'Ustawa o ochronie danych osobowych', 'Ustawa o ochronie danych osobowych'),
  ('DU/2025/620', 'Ustawa o rynku pracy i służbach zatrudnienia', 'Ustawa o rynku pracy')
on conflict (eli) do nothing;

insert into public.portal_wiedza (id, dzial, temat, tresc, podstawa, eli, zweryfikowano, kolejnosc) values
('cudz-dokument-pobytowy', 'Cudzoziemcy', 'Ważny dokument pobytowy przed rozpoczęciem pracy',
 $$Przed rozpoczęciem pracy pracodawca żąda od cudzoziemca przedstawienia ważnego dokumentu uprawniającego do pobytu w Polsce. Kopię tego dokumentu przechowuje przez cały okres wykonywania pracy. W trakcie zatrudnienia może żądać okazania aktualnego dokumentu. Portal pilnuje dat ważności karty pobytu, wizy / zezwolenia i paszportu i przypomina o nich z wyprzedzeniem 60, 30, 14 i 7 dni.$$,
 'art. 4 ust. 2–4 ustawy z 20.03.2025 r. o warunkach dopuszczalności powierzania pracy cudzoziemcom', 'DU/2025/621', '2026-10-08', 10),
('cudz-przechowywanie', 'Cudzoziemcy', 'Jak długo przechowywać dane i kopie dokumentów cudzoziemca',
 $$Dane osobowe cudzoziemca i kopie dokumentów pobytowych przechowuje się przez okres wykonywania pracy oraz 2 lata, licząc od końca roku kalendarzowego, w którym umowa się rozwiązała lub wygasła — chyba że odrębne przepisy przewidują dłuższy okres (np. 10 lat dla dokumentacji pracowniczej przy umowie o pracę).$$,
 'art. 4 ust. 4 i 6 ustawy o powierzaniu pracy cudzoziemcom', 'DU/2025/621', '2026-10-08', 20),
('cudz-umowa-pisemna', 'Cudzoziemcy', 'Umowa pisemna przed dopuszczeniem do pracy',
 $$Powierzenie pracy cudzoziemcowi wymaga zawarcia z nim umowy w formie pisemnej PRZED dopuszczeniem do pracy. Dotyczy to także umowy zlecenia. Dlatego komplet dokumentów trzeba wygenerować i podpisać najpóźniej w dniu rozpoczęcia pracy, przed jej podjęciem.$$,
 'art. 5 ust. 1 ustawy o powierzaniu pracy cudzoziemcom', 'DU/2025/621', '2026-10-08', 30),
('cudz-umowa-zrozumiala', 'Cudzoziemcy', 'Umowa w wersji zrozumiałej dla cudzoziemca',
 $$Jeżeli umowa jest po polsku, a cudzoziemiec nie zna polskiego, przed podpisaniem trzeba mu przedstawić treść umowy na piśmie w wersji dla niego zrozumiałej i przechowywać tę wersję tak długo jak dane (2 lata od końca roku zakończenia umowy). Portal robi to automatycznie: dokumenty są dwujęzyczne — polski i język obywatelstwa, tłumaczenie naprzeciw oryginału. Umowa sporządzona wyłącznie w języku obcym wymaga tłumaczenia przysięgłego na polski.$$,
 'art. 5 ust. 2–3 ustawy o powierzaniu pracy cudzoziemcom', 'DU/2025/621', '2026-10-08', 40),
('cudz-zwiazki', 'Cudzoziemcy', 'Informacja o prawie wstępowania do związków zawodowych',
 $$Cudzoziemca zatrudnionego na umowę o pracę lub umowę cywilnoprawną informuje się na piśmie, w języku dla niego zrozumiałym, o prawie wstępowania do związków zawodowych. Portal dodaje tę informację do kompletu każdego cudzoziemca (dwujęzycznie).$$,
 'art. 5 ust. 4 ustawy o powierzaniu pracy cudzoziemcom', 'DU/2025/621', '2026-10-08', 50),
('cudz-ochrona-czasowa-powiadomienie', 'Cudzoziemcy', 'Powiadomienie urzędu pracy — osoba z ochroną czasową (m.in. obywatele Ukrainy)',
 $$Pracodawca powiadamia powiatowy urząd pracy o powierzeniu pracy cudzoziemcowi korzystającemu z ochrony czasowej w ciągu 7 dni od dnia rozpoczęcia pracy — elektronicznie, przez praca.gov.pl. Ponowne powiadomienie w ciągu 7 dni jest potrzebne m.in. przy zmianie rodzaju umowy albo stanowiska. Portal pokazuje ten obowiązek w Kontroli po każdym nowym zatrudnieniu cudzoziemca.$$,
 'art. 5a ustawy o powierzaniu pracy cudzoziemcom', 'DU/2025/621', '2026-10-08', 60),
('cudz-oswiadczenie-powiadomienia', 'Cudzoziemcy', 'Oświadczenie o powierzeniu pracy — powiadomienia starosty',
 $$Gdy cudzoziemiec pracuje na podstawie oświadczenia wpisanego do ewidencji, pracodawca powiadamia starostę o podjęciu pracy w ciągu 7 dni od dnia rozpoczęcia pracy, a o niepodjęciu pracy — w ciągu 14 dni od dnia rozpoczęcia wskazanego w ewidencji. Brak powiadomienia: grzywna od 500 do 5000 zł.$$,
 'art. 70 ust. 1 i art. 84 ust. 10 ustawy o powierzaniu pracy cudzoziemcom', 'DU/2025/621', '2026-10-08', 70),
('cudz-nielegalne-powierzenie', 'Cudzoziemcy', 'Nielegalne powierzenie pracy — kiedy i jaka kara',
 $$Nielegalne jest m.in. powierzenie pracy cudzoziemcowi, który przebywa w Polsce nielegalnie, którego podstawa pobytu nie uprawnia do pracy, albo bez wymaganego zezwolenia / oświadczenia. Kara dla pracodawcy: grzywna od 3000 zł do 50 000 zł. Dlatego dokument pobytowy po terminie jest w Kontroli oznaczany na czerwono.$$,
 'art. 2 pkt 2 i art. 84 ust. 1 ustawy o powierzaniu pracy cudzoziemcom', 'DU/2025/621', '2026-10-08', 80),
('cudz-wniosek-pobyt', 'Cudzoziemcy', 'Nowa karta pobytu — termin na wniosek',
 $$Wniosek o zezwolenie na pobyt czasowy cudzoziemiec składa nie później niż w ostatnim dniu legalnego pobytu. Jeżeli wniosek złożono w terminie i bez braków formalnych, pobyt uważa się za legalny od dnia złożenia wniosku do dnia, w którym decyzja stanie się ostateczna. W takiej sytuacji od pracownika trzeba uzyskać potwierdzenie złożenia wniosku i wpisać w portalu nową datę kontroli.$$,
 'art. 105 ust. 1 i art. 108 ust. 1 ustawy o cudzoziemcach', 'DU/2013/1650', '2026-10-08', 90),
('kp-czas-okreslony', 'Umowa o pracę', 'Umowy na czas określony — limit 33 miesięcy i 3 umów',
 $$Łączny okres zatrudnienia na umowach o pracę na czas określony między tymi samymi stronami nie może przekraczać 33 miesięcy, a liczba takich umów — trzech. Po przekroczeniu limitu pracownik jest z mocy prawa zatrudniony na czas nieokreślony. Wyjątki: zastępstwo, praca dorywcza lub sezonowa, kadencja, obiektywne przyczyny po stronie pracodawcy.$$,
 'art. 25¹ § 1, 3 i 4 Kodeksu pracy', 'DU/1974/141', '2026-10-08', 110),
('kp-badania', 'Umowa o pracę', 'Badania lekarskie — wstępne i okresowe',
 $$Osoba przyjmowana do pracy podlega wstępnym badaniom lekarskim, a pracownik — badaniom okresowym. Pracodawca nie może dopuścić do pracy pracownika bez aktualnego orzeczenia lekarskiego o braku przeciwwskazań do pracy na danym stanowisku. Badania wykonuje się na podstawie skierowania od pracodawcy. Portal pilnuje daty ważności orzeczenia (30, 14 i 7 dni wcześniej).$$,
 'art. 229 § 1, 2, 4 i 4a Kodeksu pracy', 'DU/1974/141', '2026-10-08', 120),
('kp-dokumentacja', 'Umowa o pracę', 'Dokumentacja pracownicza — 10 lat',
 $$Akta osobowe i dokumentację pracowniczą przechowuje się w sposób gwarantujący poufność, integralność, kompletność i dostępność przez okres zatrudnienia oraz 10 lat, licząc od końca roku kalendarzowego, w którym stosunek pracy ustał.$$,
 'art. 94 pkt 9a–9b Kodeksu pracy', 'DU/1974/141', '2026-10-08', 130),
('zus-zgloszenie', 'ZUS', 'Zgłoszenie do ubezpieczeń — 7 dni',
 $$Pracownika i zleceniobiorcę zgłasza się do ubezpieczeń w terminie 7 dni od daty powstania obowiązku ubezpieczenia (od dnia rozpoczęcia pracy / wykonywania zlecenia). Portal pokazuje ten obowiązek w Kontroli po każdym nowym zatrudnieniu, dopóki kadrowa nie potwierdzi zgłoszenia.$$,
 'art. 36 ust. 2–4 ustawy o systemie ubezpieczeń społecznych', 'DU/1998/887', '2026-10-08', 210),
('placa-minimalna', 'Wynagrodzenie', 'Płaca minimalna i minimalna stawka godzinowa',
 $$Kwoty na dany rok ogłasza Rada Ministrów w rozporządzeniu do 15 września roku poprzedniego. Portal sam pobiera je z rejestru ELI i stosuje stawkę właściwą dla daty rozpoczęcia umowy (formularz zgłoszenia, umowa, progi dla 800+ i karty pobytu).$$,
 'art. 2 ustawy o minimalnym wynagrodzeniu za pracę', 'DU/2002/1679', '2026-10-08', 310)
on conflict (id) do update set dzial = excluded.dzial, temat = excluded.temat, tresc = excluded.tresc,
  podstawa = excluded.podstawa, eli = excluded.eli, kolejnosc = excluded.kolejnosc;
