-- PROPOZYCJA — NIE URUCHAMIAĆ bez decyzji orkiestratora.
-- Reguła bazy wiedzy (portal_wiedza) dla profili zespołu (strona zespol.html, tabela portal_pracownicy).
-- Przepisy przeczytane w tekście jednolitym Kodeksu pracy (Dz.U. 2026 poz. 1245, rejestr ELI: DU/2026/1245)
-- w dniu 2026-10-09. Kolumna eli = akt pierwotny, który śledzi prawo-monitor (DU/1974/141 jest już na liście).

insert into public.portal_wiedza (id, dzial, temat, tresc, podstawa, eli, zweryfikowano, kolejnosc) values
('zespol-dane-pracownikow', 'Dane osobowe zespołu', 'Jakie dane własnych pracowników wolno trzymać w profilach zespołu',
 $$W profilu osoby z zespołu biura wpisuje się tylko to, co potrzebne do organizacji pracy: imię i nazwisko, stanowisko, dział, zakres odpowiedzialności, służbowy e-mail i skrzynki, skrót używany w bazie klientów, nieobecność i zastępcę oraz dane kontaktowe wskazane przez tę osobę (telefon, czat Telegram do powiadomień). Imienia, nazwiska i danych kontaktowych wskazanych przez pracownika pracodawca żąda na podstawie Kodeksu pracy; stanowisko i zakres obowiązków wynikają z umowy. Prywatny numer telefonu albo prywatne konto Telegram, których pracownik sam nie wskazał jako danych kontaktowych, wolno wpisać wyłącznie za jego zgodą — brak zgody albo jej wycofanie nie może powodować żadnych negatywnych konsekwencji; po wycofaniu zgody pole się czyści. Do profilu nie wpisuje się numeru PESEL, adresu, danych o zdrowiu, wynagrodzeniu ani przyczyny nieobecności (wystarczą daty). Telefon, czat Telegram, skrzynki, zakres odpowiedzialności i notatki widzi tylko administrator portalu; pozostali użytkownicy — imię i nazwisko, stanowisko, dział, skrót, nieobecność i zastępcę. Po odejściu osoby profil oznacza się jako nieaktywny (historia zadań i przypisań klientów pozostaje czytelna), a telefon i czat Telegram usuwa się, bo przestają być potrzebne. Osoby współpracujące na podstawie innej niż umowa o pracę: te same zasady, podstawą jest wykonanie umowy i uzasadniony interes biura.$$,
 'art. 22¹ § 1 pkt 1 i 3, § 4 oraz art. 22¹ᵃ § 1–2 Kodeksu pracy; art. 5 ust. 1 lit. c i e, art. 6 ust. 1 lit. b, c i f RODO', 'DU/1974/141', '2026-10-09', 900)
on conflict (id) do update set dzial = excluded.dzial, temat = excluded.temat, tresc = excluded.tresc, podstawa = excluded.podstawa,
  eli = excluded.eli, zweryfikowano = excluded.zweryfikowano, kolejnosc = excluded.kolejnosc;
