-- Knowledge base: the statutory deadlines the Księgowość module relies on (ksieg-terminy.js,
-- page "Kalendarz terminów"). Every rule below was read in the consolidated text of the act
-- (ELI register) on the date in "zweryfikowano". prawo-monitor marks a rule do_sprawdzenia
-- when its act is amended.

insert into public.portal_prawo_akty (eli, tytul, skrot) values
  ('DU/1997/926', 'Ustawa – Ordynacja podatkowa', 'Ordynacja podatkowa'),
  ('DU/2004/535', 'Ustawa o podatku od towarów i usług', 'Ustawa o VAT'),
  ('DU/1991/350', 'Ustawa o podatku dochodowym od osób fizycznych', 'Ustawa o PIT'),
  ('DU/1992/86', 'Ustawa o podatku dochodowym od osób prawnych', 'Ustawa o CIT'),
  ('DU/1998/930', 'Ustawa o zryczałtowanym podatku dochodowym od niektórych przychodów osiąganych przez osoby fizyczne', 'Ustawa o ryczałcie'),
  ('DU/1994/591', 'Ustawa o rachunkowości', 'Ustawa o rachunkowości'),
  ('DU/1998/887', 'Ustawa o systemie ubezpieczeń społecznych', 'Ustawa o systemie ubezpieczeń społecznych'),
  ('DU/1997/776', 'Ustawa o rehabilitacji zawodowej i społecznej oraz zatrudnianiu osób niepełnosprawnych', 'Ustawa o rehabilitacji (PFRON)'),
  ('DU/1951/28', 'Ustawa o dniach wolnych od pracy', 'Ustawa o dniach wolnych od pracy')
on conflict (eli) do nothing;

insert into public.portal_wiedza (id, dzial, temat, tresc, podstawa, eli, zweryfikowano, kolejnosc) values
('ksieg-termin-przesuniecie', 'Księgowość', 'Termin w sobotę lub dzień wolny — przesunięcie',
 $$Jeżeli ostatni dzień terminu przypada na sobotę lub dzień ustawowo wolny od pracy, za ostatni dzień terminu uważa się następny dzień po dniu lub dniach wolnych od pracy. Zasada dotyczy terminów podatkowych, a przez odesłanie także należności z tytułu składek ZUS (art. 31 ustawy o systemie ubezpieczeń społecznych) i wpłat na PFRON (art. 49 ust. 1 ustawy o rehabilitacji). Nie dotyczy terminów z ustawy o rachunkowości — kalendarz portalu pokazuje je bez przesunięcia.$$,
 'art. 12 § 5 Ordynacji podatkowej', 'DU/1997/926', '2026-10-08', 500),
('ksieg-dni-wolne', 'Księgowość', 'Dni ustawowo wolne od pracy',
 $$Dniami wolnymi są niedziele oraz: 1 stycznia, 6 stycznia, pierwszy i drugi dzień Wielkiej Nocy, 1 maja, 3 maja, pierwszy dzień Zielonych Świątek, Boże Ciało, 15 sierpnia, 1 listopada, 11 listopada, 24 grudnia (Wigilia — od 1 lutego 2025 r.), 25 i 26 grudnia. Kalendarz terminów sam wylicza święta ruchome dla każdego roku.$$,
 'art. 1 ustawy z 18.01.1951 r. o dniach wolnych od pracy', 'DU/1951/28', '2026-10-08', 505),
('ksieg-vat-jpk-miesieczny', 'Księgowość', 'JPK_V7M i wpłata VAT — do 25. dnia miesiąca',
 $$Podatnik VAT rozliczający się miesięcznie składa deklarację za miesiąc do 25. dnia następnego miesiąca — jako jeden dokument elektroniczny obejmujący deklarację i ewidencję (JPK_V7M); ewidencję przesyła się łącznie z deklaracją, w terminie jej złożenia. W tym samym terminie wpłaca podatek na rachunek urzędu skarbowego.$$,
 'art. 99 ust. 1 i 11c, art. 103 ust. 1 oraz art. 109 ust. 3b ustawy o VAT', 'DU/2004/535', '2026-10-08', 510),
('ksieg-vat-jpk-kwartalny', 'Księgowość', 'JPK_V7K — rozliczenie kwartalne VAT',
 $$Mali podatnicy mogą składać deklaracje za okresy kwartalne — do 25. dnia miesiąca następującego po kwartale; w tym terminie wpłacają też podatek za kwartał. Ewidencję przesyłają co miesiąc: za pierwszy i drugi miesiąc kwartału do 25. dnia następnego miesiąca (sama ewidencja), a za ostatni miesiąc — łącznie z deklaracją kwartalną. Kwartalnie nie mogą rozliczać się m.in. podatnicy przez 12 miesięcy od rejestracji jako VAT czynni.$$,
 'art. 99 ust. 2, 3 i 3a, art. 103 ust. 2 oraz art. 109 ust. 3c ustawy o VAT', 'DU/2004/535', '2026-10-08', 515),
('ksieg-vat-ue', 'Księgowość', 'VAT-UE — informacja podsumowująca do 25. dnia',
 $$Podatnik zarejestrowany jako VAT UE składa informację podsumowującą za okresy miesięczne, elektronicznie, do 25. dnia miesiąca następującego po miesiącu, w którym powstał obowiązek podatkowy z tytułu WDT, WNT lub usług, do których stosuje się art. 28b (albo przemieszczono towary w procedurze call-off stock).$$,
 'art. 100 ust. 1 i 3 ustawy o VAT', 'DU/2004/535', '2026-10-08', 520),
('ksieg-pit-platnik-miesiecznie', 'Księgowość', 'Zaliczki i ryczałt PIT pobrane przez płatnika — do 20. dnia',
 $$Płatnik przekazuje pobrane zaliczki na podatek (wynagrodzenia, zlecenia) oraz pobrany zryczałtowany podatek do 20. dnia miesiąca następującego po miesiącu, w którym je pobrał, na rachunek urzędu skarbowego.$$,
 'art. 38 ust. 1 i art. 42 ust. 1 ustawy o PIT', 'DU/1991/350', '2026-10-08', 530),
('ksieg-pit-platnik-roczne', 'Księgowość', 'PIT-4R, PIT-8AR, PIT-11, IFT-1R — terminy roczne płatnika',
 $$Roczne deklaracje płatnika (PIT-4R, PIT-8AR) przesyła się do urzędu skarbowego do końca stycznia roku następującego po roku podatkowym. Informacje imienne (PIT-11) — urzędowi skarbowemu do końca stycznia, a podatnikowi do końca lutego. Informację o wypłatach dla osób fizycznych niebędących rezydentami (IFT-1R) — podatnikowi i urzędowi do końca lutego.$$,
 'art. 38 ust. 1a, art. 39 ust. 1, art. 42 ust. 1a i ust. 2 pkt 2 oraz art. 42g ust. 1 ustawy o PIT', 'DU/1991/350', '2026-10-08', 535),
('ksieg-pit-zaliczki', 'Księgowość', 'Zaliczki PIT przedsiębiorcy (skala, liniowy) — do 20. dnia',
 $$Zaliczki miesięczne wpłaca się do 20. dnia każdego miesiąca za miesiąc poprzedni, a kwartalne (mali podatnicy i rozpoczynający działalność) — do 20. dnia miesiąca następującego po kwartale. Zaliczkę za ostatni miesiąc lub ostatni kwartał roku wpłaca się do 20 stycznia następnego roku.$$,
 'art. 44 ust. 3, 3f, 3g, 3h i 6 ustawy o PIT', 'DU/1991/350', '2026-10-08', 540),
('ksieg-pit-zeznania', 'Księgowość', 'PIT-36, PIT-36L, PIT-37 — od 15 lutego do 30 kwietnia',
 $$Zeznanie roczne składa się od 15 lutego do 30 kwietnia roku następującego po roku podatkowym; zeznanie złożone wcześniej uznaje się za złożone 15 lutego. Przed upływem tego terminu wpłaca się różnicę między podatkiem należnym a sumą zaliczek. Podatnik prowadzący księgi rachunkowe w tym samym terminie przekazuje elektronicznie sprawozdanie finansowe Szefowi KAS.$$,
 'art. 45 ust. 1, 1a, 4 i 5 ustawy o PIT', 'DU/1991/350', '2026-10-08', 545),
('ksieg-ryczalt', 'Księgowość', 'Ryczałt od przychodów ewidencjonowanych — wpłaty i PIT-28',
 $$Ryczałt wpłaca się za każdy miesiąc do 20. dnia następnego miesiąca, a za grudzień — do 20 stycznia. Kwartalnie (do 20. dnia miesiąca po kwartale, za ostatni kwartał do 20 stycznia) mogą płacić rozpoczynający działalność i podatnicy, których przychody w poprzednim roku nie przekroczyły równowartości 200 000 euro. Zeznanie PIT-28 składa się od 15 lutego do 30 kwietnia.$$,
 'art. 21 ust. 1, 1a, 1b i ust. 2 pkt 2 ustawy o zryczałtowanym podatku dochodowym', 'DU/1998/930', '2026-10-08', 550),
('ksieg-cit-zaliczki', 'Księgowość', 'Zaliczki CIT — do 20. dnia',
 $$Zaliczki miesięczne wpłaca się do 20. dnia każdego miesiąca za miesiąc poprzedni; kwartalne (mali podatnicy i rozpoczynający działalność w pierwszym roku) — do 20. dnia miesiąca następującego po kwartale. Zaliczki za ostatni miesiąc lub kwartał nie wpłaca się, jeżeli przed terminem jej wpłaty podatnik złoży zeznanie i zapłaci podatek.$$,
 'art. 25 ust. 1, 1a, 1b i 1c ustawy o CIT', 'DU/1992/86', '2026-10-08', 560),
('ksieg-cit-roczne', 'Księgowość', 'CIT-8, CIT-8E i CIT-ST — terminy roczne',
 $$Zeznanie CIT-8 składa się do końca trzeciego miesiąca roku następnego i w tym terminie wpłaca podatek (31 marca przy roku podatkowym równym kalendarzowemu). Spółka na ryczałcie od dochodów spółek składa w tym samym terminie deklarację CIT-8E. Podatnik posiadający zakłady (oddziały) w innej jednostce samorządu niż siedziba składa do 31 marca informację CIT-ST według stanu na 31 grudnia roku poprzedniego.$$,
 'art. 27 ust. 1, art. 28 ust. 1 i art. 28r ust. 1 ustawy o CIT', 'DU/1992/86', '2026-10-08', 565),
('ksieg-cit-wht', 'Księgowość', 'Podatek u źródła (CIT) — do 7. dnia i IFT-2R',
 $$Płatnik przekazuje pobrany zryczałtowany podatek od wypłat do 7. dnia miesiąca następującego po miesiącu, w którym go pobrał. Informację o wypłatach i pobranym podatku dla zagranicznych podatników (IFT-2R) przesyła podatnikowi i urzędowi skarbowemu do końca trzeciego miesiąca roku następującego po roku podatkowym, w którym dokonano wypłat.$$,
 'art. 26 ust. 3 i 3a ustawy o CIT', 'DU/1992/86', '2026-10-08', 570),
('ksieg-zus-terminy', 'Księgowość', 'ZUS — składki i deklaracje: 5., 15. albo 20. dzień miesiąca',
 $$Płatnik przesyła deklarację rozliczeniową i raporty imienne oraz opłaca składki za dany miesiąc w tym samym terminie: do 5. dnia następnego miesiąca — jednostki budżetowe i samorządowe zakłady budżetowe; do 15. dnia — płatnicy posiadający osobowość prawną (np. spółka z o.o.); do 20. dnia — pozostali płatnicy (m.in. jednoosobowa działalność, spółki osobowe). Kto opłaca składki wyłącznie za siebie, przesyła tylko deklarację. Składki społeczne, zdrowotną i na fundusze opłaca się jedną wpłatą na numer rachunku składkowego.$$,
 'art. 47 ust. 1, 2 i 4 ustawy o systemie ubezpieczeń społecznych', 'DU/1998/887', '2026-10-08', 580),
('ksieg-pfron', 'Księgowość', 'PFRON — wpłata i deklaracja do 20. dnia',
 $$Pracodawca zatrudniający co najmniej 25 pracowników w przeliczeniu na pełny wymiar czasu pracy, który nie osiąga 6% wskaźnika zatrudnienia osób niepełnosprawnych, dokonuje wpłat na PFRON do 20. dnia miesiąca następującego po miesiącu, w którym powstał obowiązek, składając równocześnie deklarację elektroniczną. Do wpłat stosuje się odpowiednio Ordynację podatkową.$$,
 'art. 21 ust. 1 oraz art. 49 ust. 1 i 2 ustawy o rehabilitacji zawodowej i społecznej oraz zatrudnianiu osób niepełnosprawnych', 'DU/1997/776', '2026-10-08', 590),
('ksieg-sprawozdanie-finansowe', 'Księgowość', 'Sprawozdanie finansowe — 3 miesiące, 6 miesięcy, 15 dni',
 $$Roczne sprawozdanie finansowe sporządza się nie później niż w ciągu 3 miesięcy od dnia bilansowego, a zatwierdza nie później niż 6 miesięcy od dnia bilansowego (31 marca i 30 czerwca przy roku obrotowym równym kalendarzowemu). W ciągu 15 dni od zatwierdzenia kierownik jednostki składa je w rejestrze sądowym wraz z uchwałą o zatwierdzeniu i podziale zysku lub pokryciu straty. Jeżeli sprawozdania nie zatwierdzono w terminie, składa się je w ciągu 15 dni po tym terminie, a następnie ponownie w ciągu 15 dni po zatwierdzeniu.$$,
 'art. 52 ust. 1, art. 53 ust. 1 oraz art. 69 ust. 1 i 2 ustawy o rachunkowości', 'DU/1994/591', '2026-10-08', 600),
('ksieg-sprawozdanie-kas', 'Księgowość', 'Sprawozdanie finansowe do Szefa KAS — kto i kiedy',
 $$Podatnik CIT obowiązany do sporządzenia sprawozdania finansowego przekazuje je elektronicznie Szefowi KAS w ciągu 15 dni od zatwierdzenia — obowiązek nie dotyczy podmiotów, które składają sprawozdania do Krajowego Rejestru Sądowego (np. spółek z o.o.). Podatnik PIT prowadzący księgi rachunkowe przekazuje sprawozdanie Szefowi KAS przed upływem terminu na złożenie zeznania rocznego.$$,
 'art. 27 ust. 2 ustawy o CIT; art. 45 ust. 5 ustawy o PIT', 'DU/1992/86', '2026-10-08', 605)
on conflict (id) do update set dzial = excluded.dzial, temat = excluded.temat, tresc = excluded.tresc,
  podstawa = excluded.podstawa, eli = excluded.eli, kolejnosc = excluded.kolejnosc;
