-- Umowy — the price list as data, taken from Załącznik nr 1 of the prepaid templates of 2026
-- (Sp. z o.o.: księgi rachunkowe; JDG: KPiR / ryczałt). Seeded once: later changes are made by the
-- administrator on the page and recorded in umowy_cennik_historia. `kod` marks what the forecast
-- calculator uses; `stala` = a recurring service that may enter the first monthly rate.
insert into public.umowy_cennik (rodzina, grupa, kod, nazwa, jednostka, prog, cena, cena_opis, stala, kolejnosc, zmienil)
select v.rodzina, v.grupa, v.kod, v.nazwa, v.jednostka, v.prog, v.cena, v.cena_opis, v.stala, v.kolejnosc, 'migracja'
from (values
  ('SPZOO', 'Prowadzenie ksiąg rachunkowych wraz z ewidencją VAT', 'zapisy', 'Brak dokumentów w danym miesiącu (0 zapisów na kontach Księgi)', 'miesiąc', 0, 350, null, true, 10),
  ('SPZOO', 'Prowadzenie ksiąg rachunkowych wraz z ewidencją VAT', 'zapisy', 'Do 10 zapisów na kontach Księgi', 'miesiąc', 10, 450, null, true, 20),
  ('SPZOO', 'Prowadzenie ksiąg rachunkowych wraz z ewidencją VAT', 'zapisy', 'Do 20 zapisów na kontach Księgi', 'miesiąc', 20, 600, null, true, 30),
  ('SPZOO', 'Prowadzenie ksiąg rachunkowych wraz z ewidencją VAT', 'zapisy', 'Do 30 zapisów na kontach Księgi', 'miesiąc', 30, 700, null, true, 40),
  ('SPZOO', 'Prowadzenie ksiąg rachunkowych wraz z ewidencją VAT', 'zapisy', 'Do 50 zapisów na kontach Księgi', 'miesiąc', 50, 900, null, true, 50),
  ('SPZOO', 'Prowadzenie ksiąg rachunkowych wraz z ewidencją VAT', 'zapis_kolejny', 'Opłata za każdy kolejny zapis na koncie', 'zapis', null, 11, null, true, 60),
  ('SPZOO', 'Prowadzenie ksiąg rachunkowych wraz z ewidencją VAT', 'srodek_trwaly', 'Prowadzenie ewidencji środków trwałych i wartości niematerialnych i prawnych wraz z opracowaniem i aktualizowaniem planu amortyzacji', 'środek trwały', null, 50, null, true, 70),
  ('SPZOO', 'Prowadzenie ksiąg rachunkowych wraz z ewidencją VAT', null, 'Wystawienie not księgowych, potwierdzeń sald itp. wraz z ich wysłaniem', 'szt.', null, 30, '30,00 + opłata pocztowa', false, 80),
  ('SPZOO', 'Prowadzenie ksiąg rachunkowych wraz z ewidencją VAT', 'vat_jpk', 'Sporządzanie deklaracji VAT JPK', 'deklaracja', null, 100, null, true, 90),
  ('SPZOO', 'Prowadzenie ksiąg rachunkowych wraz z ewidencją VAT', 'vat_ue', 'Sporządzanie informacji VAT UE', 'informacja', null, 100, null, true, 100),
  ('SPZOO', 'Prowadzenie ksiąg rachunkowych wraz z ewidencją VAT', 'roznice_kursowe', 'Rozliczenie różnic kursowych', 'dokument', null, 15, null, true, 110),
  ('SPZOO', 'Prowadzenie ksiąg rachunkowych wraz z ewidencją VAT', null, 'Sporządzanie sprawozdania finansowego po zakończeniu roku oraz bilansu zysków i strat', 'rok', null, null, 'równowartość średniej miesięcznej faktury netto (suma faktur netto za usługi w danym roku obrotowym, z wyłączeniem tej usługi, podzielona przez liczbę miesięcy obsługi w tym roku)', false, 120),
  ('SPZOO', 'Prowadzenie ksiąg rachunkowych wraz z ewidencją VAT', null, 'Korekta z winy klienta', 'dokument', null, 200, 'od 200,00', false, 130),
  ('SPZOO', 'Prowadzenie ksiąg rachunkowych wraz z ewidencją VAT', null, 'Przygotowanie ZPA, ZFA', 'dokument', null, 100, null, false, 140),
  ('SPZOO', 'Prowadzenie ksiąg rachunkowych wraz z ewidencją VAT', null, 'Sporządzenie rocznych deklaracji podatkowych od wynagrodzeń, przekazanie ich podatnikowi i złożenie/wysłanie do właściwego urzędu (PIT-11, PIT-40, PIT-8AR, PIT-4R etc.)', 'dokument', null, 70, null, false, 150),
  ('SPZOO', 'Prowadzenie ksiąg rachunkowych wraz z ewidencją VAT', null, 'Sporządzenie dokumentów rejestrowych do rejestracji jako płatnik VAT', null, null, 400, null, false, 160),
  ('SPZOO', 'Prowadzenie ksiąg rachunkowych wraz z ewidencją VAT', null, 'Sporządzenie deklaracji VAT-UE, VAT 9M, VAT 8', 'deklaracja', null, 100, null, false, 170),
  ('SPZOO', 'Prowadzenie ksiąg rachunkowych wraz z ewidencją VAT', null, 'Korekta naliczenia listy płac i inne korekty wynikające z winy Zleceniodawcy', 'osoba', null, 100, null, false, 180),
  ('SPZOO', 'Prowadzenie ksiąg rachunkowych wraz z ewidencją VAT', 'zus_dra', 'Dokument ZUS DRA za osobę prowadzącą działalność', 'dokument', null, 50, null, true, 190),
  ('SPZOO', 'Prowadzenie ksiąg rachunkowych wraz z ewidencją VAT', null, 'Zmiana składki ZUS', 'dokument', null, 100, null, false, 200),
  ('SPZOO', 'Czynności dodatkowe wykraczające poza przedmiot umowy', null, 'Wystawienie faktury w imieniu i na życzenie Podatnika', 'dokument', null, 30, null, false, 300),
  ('SPZOO', 'Czynności dodatkowe wykraczające poza przedmiot umowy', null, 'Wystawienie zaświadczeń o zarobkach dla pracownika', 'dokument', null, 30, null, false, 310),
  ('SPZOO', 'Czynności dodatkowe wykraczające poza przedmiot umowy', null, 'Sporządzenie dokumentów aktualizacyjnych / zgłoszeniowych do KRS', null, null, 500, 'od 500,00', false, 320),
  ('SPZOO', 'Czynności dodatkowe wykraczające poza przedmiot umowy', null, 'Sporządzanie innych deklaracji podatkowych (np. dla podatku od czynności cywilno-prawnych, nieruchomości, NIP-8 etc.), raportów GUS', null, null, 100, null, false, 330),
  ('SPZOO', 'Czynności dodatkowe wykraczające poza przedmiot umowy', null, 'Prowadzenie / uczestnictwo w postępowaniu kontrolnym / sprawdzającym / wyjaśniającym - każda rozpoczęta godzina', 'godzina', null, 150, '150,00 zł + zwrot kosztów', false, 340),
  ('SPZOO', 'Czynności dodatkowe wykraczające poza przedmiot umowy', null, 'Pisanie pism na życzenie Podatnika', 'dokument', null, 100, 'od 100,00', false, 350),
  ('SPZOO', 'Czynności dodatkowe wykraczające poza przedmiot umowy', null, 'Przygotowanie protokołu zdawczo-odbiorczego przy zdawaniu dokumentacji księgowej', null, null, 50, null, false, 360),
  ('SPZOO', 'Czynności dodatkowe wykraczające poza przedmiot umowy', null, 'Prowadzenie magazynu (do 10 artykułów), każdy kolejny', null, null, null, '100,00 / 7,00', false, 370),
  ('SPZOO', 'Usługi kadrowo-płacowe', 'uop', 'Pracownik - umowa o pracę', 'pracownik', null, 80, null, true, 400),
  ('SPZOO', 'Usługi kadrowo-płacowe', 'uz', 'Pracownik - umowa zlecenie', 'pracownik', null, 50, null, true, 410),
  ('SPZOO', 'Usługi kadrowo-płacowe', null, 'Przygotowanie umowy o zlecenia, umowy o dzieło', 'komplet dokumentów', null, 50, null, false, 420),
  ('SPZOO', 'Usługi kadrowo-płacowe', null, 'Przygotowanie umowy o pracę', 'komplet dokumentów', null, 90, null, false, 430),
  ('SPZOO', 'Usługi kadrowo-płacowe', null, 'Zgłaszanie oraz aktualizacja danych w ZUS', 'dokument', null, 30, null, false, 440),
  ('SPZOO', 'Usługi kadrowo-płacowe', null, 'Przygotowanie załącznika nr 1 do karty pobytu', 'stanowisko pracy', null, 100, null, false, 450),
  ('SPZOO', 'Usługi kadrowo-płacowe', null, 'Powiadomienie o powierzeniu wykonywania pracy obywatelowi Ukrainy (PSZ-PPWPU)', null, null, 100, null, false, 460),
  ('SPZOO', 'Usługi kadrowo-płacowe', null, 'Oświadczenia o powierzeniu wykonywania pracy cudzoziemcowi', null, null, 150, null, false, 470),
  ('SPZOO', 'Usługi kadrowo-płacowe', null, 'Zezwolenia na pracę sezonową cudzoziemca', null, null, 150, null, false, 480),
  ('SPZOO', 'Usługi kadrowo-płacowe', null, 'Zezwolenia na pracę cudzoziemca', null, null, 250, null, false, 490),
  ('SPZOO', 'Usługi kadrowo-płacowe', null, 'Wyrobienie karty czasowego pobytu dla pracowników (przygotowanie kompletu dokumentów)', null, null, 500, null, false, 500),
  ('SPZOO', 'Usługi kadrowo-płacowe', null, 'Wyrobienie karty czasowego pobytu dla pracowników (przygotowanie dokumentów + prowadzenie sprawy)', null, null, 1000, null, false, 510),
  ('SPZOO', 'Usługi kadrowo-płacowe', null, 'Przygotowanie A1 dla delegacji', null, null, 100, null, false, 520),
  ('SPZOO', 'Usługi kadrowo-płacowe', null, 'EKUZ', null, null, 100, null, false, 530),
  ('SPZOO', 'Usługi kadrowo-płacowe', null, 'Świadectwo kierowcy', null, null, 200, null, false, 540),
  ('SPZOO', 'Usługi kadrowo-płacowe', null, 'Zezwolenie na kraje', null, null, 150, null, false, 550),
  ('SPZOO', 'Usługi kadrowo-płacowe', null, 'KOD-95', null, null, null, 'indywidualnie', false, 560),
  ('SPZOO', 'Usługi kadrowo-płacowe', null, 'Pozostałe usługi ustalane dodatkowo', null, null, null, 'indywidualnie', false, 570),
  ('JDG', 'Usługi księgowe', 'zapisy', 'Do 5 zapisów na kontach Księgi', 'miesiąc', 5, 250, null, true, 10),
  ('JDG', 'Usługi księgowe', 'zapisy', 'Do 10 zapisów na kontach Księgi', 'miesiąc', 10, 300, null, true, 20),
  ('JDG', 'Usługi księgowe', 'zapisy', 'Do 20 zapisów na kontach Księgi', 'miesiąc', 20, 450, null, true, 30),
  ('JDG', 'Usługi księgowe', 'zapisy', 'Do 30 zapisów na kontach Księgi', 'miesiąc', 30, 550, null, true, 40),
  ('JDG', 'Usługi księgowe', 'zapisy', 'Do 50 zapisów na kontach Księgi', 'miesiąc', 50, 750, null, true, 50),
  ('JDG', 'Usługi księgowe', 'zapis_kolejny', 'Opłata za każdy kolejny zapis na koncie', 'zapis', null, 11, null, true, 60),
  ('JDG', 'Usługi księgowe', 'vat_jpk', 'Sporządzanie deklaracji VAT + JPK', 'deklaracja', null, 100, null, true, 70),
  ('JDG', 'Usługi księgowe', 'roznice_kursowe', 'Rozliczenie różnic kursowych', 'dokument', null, 15, null, true, 80),
  ('JDG', 'Usługi księgowe', null, 'Korekta z winy klienta', 'dokument', null, 100, 'od 100', false, 90),
  ('JDG', 'Usługi księgowe', null, 'Przygotowanie ZPA, ZFA', 'dokument', null, 100, null, false, 100),
  ('JDG', 'Usługi księgowe', null, 'Sporządzenie rocznych deklaracji podatkowych od wynagrodzeń, przekazanie ich podatnikowi i złożenie/wysłanie do właściwego urzędu (PIT-11, PIT-40, PIT-8AR, PIT-4R etc.)', 'dokument', null, 50, null, false, 110),
  ('JDG', 'Usługi księgowe', null, 'Sporządzenie dokumentów rejestrowych do rejestracji jako płatnik VAT', null, null, 300, null, false, 120),
  ('JDG', 'Usługi księgowe', null, 'Sporządzenie deklaracji VAT-UE, VAT 9M, VAT 8', 'deklaracja', null, 100, null, false, 130),
  ('JDG', 'Usługi księgowe', null, 'Korekta naliczenia listy płac i inne korekty wynikające z winy Zleceniodawcy', 'osoba', null, 100, null, false, 140),
  ('JDG', 'Usługi księgowe', 'srodek_trwaly', 'Prowadzenie ewidencji środków trwałych i wartości niematerialnych i prawnych wraz z opracowaniem i aktualizowaniem planu amortyzacji', 'środek trwały', null, 100, null, true, 150),
  ('JDG', 'Usługi księgowe', null, 'Wystawienie not księgowych, potwierdzeń sald itp. wraz z ich wysłaniem', 'szt.', null, 30, '30 + opłata pocztowa', false, 160),
  ('JDG', 'Czynności dodatkowe wykraczające poza przedmiot umowy', null, 'Wystawienie faktury w imieniu i na życzenie Podatnika', 'dokument', null, 30, null, false, 300),
  ('JDG', 'Czynności dodatkowe wykraczające poza przedmiot umowy', null, 'Wystawienie zaświadczeń o zarobkach dla pracownika', 'dokument', null, 30, null, false, 310),
  ('JDG', 'Czynności dodatkowe wykraczające poza przedmiot umowy', null, 'Wystawienie zaświadczeń o niezaleganiu w opłacaniu składek ZUS oraz zaświadczeń o niezaleganiu w opłacaniu podatków US', 'dokument', null, 50, null, false, 320),
  ('JDG', 'Czynności dodatkowe wykraczające poza przedmiot umowy', null, 'Sporządzenie dokumentów aktualizacyjnych / zgłoszeniowych do CEIDG', null, null, 300, 'od 300', false, 330),
  ('JDG', 'Czynności dodatkowe wykraczające poza przedmiot umowy', null, 'Sporządzanie innych deklaracji podatkowych (np. dla podatku od czynności cywilno-prawnych, nieruchomości etc.)', null, null, 100, 'od 100,00', false, 340),
  ('JDG', 'Czynności dodatkowe wykraczające poza przedmiot umowy', null, 'Prowadzenie / uczestnictwo w postępowaniu kontrolnym / sprawdzającym / wyjaśniającym - każda rozpoczęta godzina', 'godzina', null, 150, '150 + zwrot kosztów', false, 350),
  ('JDG', 'Czynności dodatkowe wykraczające poza przedmiot umowy', null, 'Pisanie pism na życzenie Podatnika', 'dokument', null, 100, 'od 100', false, 360),
  ('JDG', 'Czynności dodatkowe wykraczające poza przedmiot umowy', null, 'Przygotowanie protokołu zdawczo-odbiorczego przy zdawaniu dokumentacji księgowej', null, null, 50, null, false, 370),
  ('JDG', 'Usługi kadrowe', 'uz', 'Rozliczanie wynagrodzeń ze składkami ZUS na umowie zlecenia', 'pracownik', null, 50, null, true, 400),
  ('JDG', 'Usługi kadrowe', 'uop', 'Rozliczanie wynagrodzeń ze składkami ZUS na umowie o pracę', 'pracownik', null, 80, null, true, 410),
  ('JDG', 'Usługi kadrowe', null, 'Przygotowanie dokumentów do umowy zlecenia', 'komplet dokumentów', null, 50, null, false, 420),
  ('JDG', 'Usługi kadrowe', null, 'Przygotowanie dokumentów do umowy o pracę', 'komplet dokumentów', null, 80, null, false, 430),
  ('JDG', 'Usługi kadrowe', null, 'Zgłaszanie oraz aktualizacja danych w ZUS', 'dokument', null, 30, null, false, 440),
  ('JDG', 'Usługi kadrowe', null, 'Przygotowanie załącznika nr 1 do karty pobytu', null, null, 100, null, false, 450),
  ('JDG', 'Usługi kadrowe', null, 'Powiadomienie o powierzeniu wykonywania pracy obywatelowi Ukrainy (PSZ-PPWPU)', null, null, 100, null, false, 460),
  ('JDG', 'Usługi kadrowe', null, 'Oświadczenia o powierzeniu wykonywania pracy cudzoziemcowi', null, null, 150, null, false, 470),
  ('JDG', 'Usługi kadrowe', null, 'Zezwolenia na pracę sezonową cudzoziemca', null, null, 150, null, false, 480),
  ('JDG', 'Usługi kadrowe', null, 'Zezwolenia na pracę cudzoziemca', null, null, 250, null, false, 490),
  ('JDG', 'Usługi kadrowe', null, 'Wyrobienie karty czasowego pobytu dla pracowników', null, null, null, 'indywidualnie', false, 500),
  ('JDG', 'Usługi kadrowe', null, 'Przygotowanie A1 dla delegacji', null, null, 100, 'od 100', false, 510),
  ('JDG', 'Usługi kadrowe', null, 'Pozostałe usługi ustalane dodatkowo', null, null, null, 'indywidualnie', false, 520)
) as v(rodzina, grupa, kod, nazwa, jednostka, prog, cena, cena_opis, stala, kolejnosc)
where not exists (select 1 from public.umowy_cennik);
